---
- name: install calicoctl pkg
  get_url:
    url: "{{ calico_pkg_url }}"
    dest: /usr/local/bin
    mode: "0755"

- name: generate calico-etcd.yaml {{ calico_version }}
  template:
    src: "{{ calico_version }}/calico-etcd.yaml"
    dest: calico-etcd.yaml

- name: create calico resource
  shell: |
    export KUBECONFIG=/etc/kubernetes/admin.conf
    kubectl apply -f calico-etcd.yaml
  register: calico_install_result
  ignore_errors: yes

- name: show install calico log
  debug:
    msg:
      - "{{ calico_install_result.stdout_lines }}"
      - "{{ calico_install_result.stderr_lines }}"
