---
apiVersion: v1
kind: ConfigMap
metadata:
  name: pushgateway-web-config
  namespace: prometheus
  labels:
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: EnsureExists
data:
  web.yml: |
    basic_auth_users:
      pushgateway: $2y$05$kfShlXxOEllGGtliJbNSvu7.43U2Pd4bNF/OM/OwJocuT5KKKAiEi