---
bind_master_role: False
bind_slave_role: False

bind_foreman_rev_net: 2.168.192
bind_foreman_rev_ip: 1

bind_packages:
  - bind
  - bind-*

bind_service: named

bind_root_dir: /var/named
bind_data_dir: data
bind_conf_dir: "/etc/named"
bind_auth_file: "{{ bind_conf_dir }}/auth_transfer.conf"

bind_owner: root
bind_group: named

bind_bindkeys_file: "/etc/named.iscdlv.key"
bind_pid_file: "/run/named/named.pid"
bind_session_keyfile: "/run/named/session.key"

# Custom location for master zone files
bind_master_zone_dir: "{{ bind_root_dir }}/{{ bind_data_dir }}"
bind_slave_zone_dir: "{{ bind_root_dir }}/slaves"


bind_zones:
  - freedom.org
  - consul.freedom.org
  - k8s.freedom.org

bind_rev_zones:
  - {ip: "{{ bind_foreman_rev_net }}", domain_name: "freedom.org"}