---
- name: "config redis data dir for instance {{ redis_port }}"
  tags:
    - configure-redis
  file:
    path: "{{ redis_data_dir }}/{{ redis_port }}"
    state: directory

- name: "config redis for instnace {{ redis_port }}"
  tags:
    - configure-redis
  template:
    src: redis_cluster_single_host_redis.conf.j2
    dest: "{{ redis_conf_dir }}/redis_{{ redis_port }}.conf"

- name: "config redis.sh for instance {{ redis_port }}"
  tags:
    - configure-redis
  template:
    src: redis.sh.j2
    dest: "{{ redis_installation_dir }}/redis.sh"
    mode: "0755"