---
- name: "config redis data dir for instance {{ redis_port }}"
  tags:
    - configure-redis
  file:
    path: "{{ redis_data_dir }}/{{ redis_port }}"
    state: directory

- name: "config redis for instnace {{ redis_port }}"
  tags:
    - configure-redis
  template:
    src: redis.conf.j2
    dest: "{{ redis_installation_dir }}/redis-{{ redis_port }}.conf"