---
- name: generate kubernetes storageclass items
  hosts: localhost
  user: root
  tasks:
    - name: generate kubernetes storageclass items
      template:
        src: nfs.j2
        dest: "{{ storagecalss_output_dir }}/deploy-kubernetes-storageclass-nfs-{{ item.name }}.yaml"
      with_items:
          - name: infra
            nfs_server: infra.nfs.freedom.org
            nfs_server_shared_dir: /data/kubernetes-datastorage-nfs-pvc/infra
          - name: redis
            nfs_server: redis.nfs.freedom.org
            nfs_server_shared_dir: /data/kubernetes-datastorage-nfs-pvc/redis
          - name: mysql
            nfs_server: mysql.nfs.freedom.org
            nfs_server_shared_dir: /data/kubernetes-datastorage-nfs-pvc/mysql