---
- include: roles/common/handlers/main.yml

- include: roles/consul/handlers/main.yml

- name: start-haproxy
  service: name=haproxy state=started enabled=yes

- name: reload-haproxy
  service: name=haproxy state=reloaded enabled=yes

- name: restart-rsyslog
  service: name=rsyslog state=restarted enabled=yes

- name: systemctl-enable-haproxy
  systemd:
    name: haproxy
    enabled: yes
