# 配置启动elasticsearch服务的用户名密码信息。
user_name: "elk"
user_id: 2000
user_passwd: "$6$PohsRJR7Od91yrUp$lsSHQEnLIMFicF0Fjfdd0mPOK8TLIXX6NBOjIhz5fxZdL87N65KWnc/lZpkDBTjyWi8Qe6A41f8uXIpVXMEIm."
user_shell: "/bin/bash"


# 配置elasticsearch包信息。
pkg_version: "{{ elasticesearch_version }}"
pkg: "elasticsearch-{{ pkg_version }}"
pkg_url: "ftp://foreman.example.com/pub/elk/elasticsearch-{{ pkg_version }}-linux-x86_64.tar.gz"
pkg_dest: "/usr/local/"
pkg_link_dir: "/usr/local/elasticsearch"


# 配置elasticsearch配置文件基本变量信息。
create_config_file: true
config_template: "elasticsearch.yml.j2"
config_file: "elasticsearch.yml"

node_name: "{{ node_name }}"
cluster_name: "{{ cluster_name }}"
bootstrap_memory_lock: false
network_host: 0.0.0.0
http_port: 9200
cluster_hosts: "{{ cluster_hosts }}"
minimum_cluster_nodes: "{{ minimum_cluster_nodes }}"  # 此参数用于版本6。
bootstrap_system_call_filter: false
http_cors_enabled: true
http_cors_allow_origin: /.*/


# elasticsearch服务进程信息
elasticsearch_bin: "{{ pkg_link_dir }}/bin/elasticsearch -d"
elasticsearch_proc: "{{ pkg_link_dir }}/jdk/bin/java"


# 系统调优参数
sysctl_file: /etc/sysctl.d/100-elk.conf


# 配置elasticsearch插件