- name: systemctl-daemon-reload
  systemd:
    daemon_reload: yes

- name: enable-grafana-server
  service:
    name: grafana-server
    enabled: yes

- name: restart-grafana-server
  service:
    name: grafana-server
    state: restarted
    enabled: yes