---
- name: generate configuration file
  template:
    src: "{{ item.src}}"
    dest: "{{ item.dest }}"
    owner: "{{ nginx_owner }}"
    group: "{{ nginx_group }}"
  with_items:
    - { src: default.conf.j2, dest: "{{ nginx_sub_conf_dir }}/default.conf }
  notify:
    - reload-nginx