apiVersion: v1
kind: Service
metadata:
  name: keycloak-mysql
  namespace: keycloak
  labels:
    name: keycloak-mysql
spec:
  type: ClusterIP
  ports:
    - port: 3306        # 服务访问端口
      targetPort: 3306  # 容器端口
  selector:
    name: keycloak-mysql


---
apiVersion: v1
kind: Service
metadata:
  name: keycloak-mysql-nodeport
  namespace: keycloak
  labels:
    name: keycloak-mysql-nodeport
spec:
  type: NodePort
  ports:
    - port: 3306        # 服务访问端口
      targetPort: 3306  # 容器端口
  selector:
    name: keycloak-mysql