---
- name: generate redis cluster playbook
  hosts: localhost
  gather_facts: True

  tasks:
    - name: generate playbook
      template:
        src: dump_redis_cluster_rdb_files_template.yml.j2
        dest: "{{ ansible_playbooks_output_dir }}/0-dump-redis-cluster-rdb-files-{{ item.service_name }}.yml"
      with_items:
        - {
            service_name: 'single-host-multi-instance-type',
            instances: [
              {"host": '192.168.255.106', "port": 7001 },
              {"host": '192.168.255.106', "port": 7002 },
              {"host": '192.168.255.106', "port": 7003 },
              {"host": '192.168.255.106', "port": 7004 },
              {"host": '192.168.255.106', "port": 7005 },
              {"host": '192.168.255.106', "port": 7006 }
            ]
        }