---
- name: generate single host redis cluster playbook
  hosts: localhost
  gather_facts: True

  tasks:
    - name: generate redis cluster single host type index playbook
      tags: generate-redis_cluster_single_host_type-index-playbook
      template:
        src: single_host_redis_cluster_template_index.yml
        dest: "{{ output_dir }}/0-{{ item.service_name }}-{{ item.host }}-index.yml"
        variable_start_string: '[['
        variable_end_string: ']]'
      with_items:
        - { service_name: 'redis_cluster_single_host',
            host: '192.168.255.106',
            redis_version: '3.0.3',
            redis_ports: [7001, 7002, 7003, 7004, 7005, 7006, 7007, 7008, 7009, 7010]
        }

    - name: generate redis cluster single host type node playbook
      tags: generate-redis_cluster_single_host_type-node-playbook
      template:
        src: single_host_redis_cluster_template_node.yml
        dest: "{{ output_dir }}/0-{{ item.service_name }}-{{ item.host }}-node-{{ item.redis_port }}.yml"
        variable_start_string: '[['
        variable_end_string: ']]'
      with_items:
        - { service_name: 'redis_cluster_single_host', host: '192.168.255.106', redis_port: 7001 }
        - { service_name: 'redis_cluster_single_host', host: '192.168.255.106', redis_port: 7002 }
        - { service_name: 'redis_cluster_single_host', host: '192.168.255.106', redis_port: 7003 }
        - { service_name: 'redis_cluster_single_host', host: '192.168.255.106', redis_port: 7004 }
        - { service_name: 'redis_cluster_single_host', host: '192.168.255.106', redis_port: 7005 }
        - { service_name: 'redis_cluster_single_host', host: '192.168.255.106', redis_port: 7006 }
        - { service_name: 'redis_cluster_single_host', host: '192.168.255.106', redis_port: 7007 }
        - { service_name: 'redis_cluster_single_host', host: '192.168.255.106', redis_port: 7008 }
        - { service_name: 'redis_cluster_single_host', host: '192.168.255.106', redis_port: 7009 }
        - { service_name: 'redis_cluster_single_host', host: '192.168.255.106', redis_port: 7010 }