---

- name: get redis cluster rbd files
  hosts: 192.168.255.106
  user: root

  tasks:
    - name: 'copy redis cluster rbd files from remote hosts'
      fetch:
        src: /home/{{ item.host }}-{{ item.port }}.rdb
        dest: /home
      with_items:
        - { host: 192.168.255.106, port: 7001 }
        - { host: 192.168.255.106, port: 7002 }
        - { host: 192.168.255.106, port: 7003 }
        - { host: 192.168.255.106, port: 7004 }
        - { host: 192.168.255.106, port: 7005 }
        - { host: 192.168.255.106, port: 7006 }