---
- name: elasticsearch host node01.es.freedom.org
  hosts: node01.es.freedom.org
  user: root
  roles:
    - role: 000-base-000-common
      tags:
        - common

    - role: 000-base-001-consul
      tags:
        - consul-agent
      vars:
        consul_template_role: True
        consul_agent_role: True
        consul_agent_items:
          services:
            - name: elasticsearch-db
              port: 9200
            - name: elasticsearch-transport
              port: 9300
            - name: consul-agent
              port: 8500

    - role: 000-base-002-zabbix
      tags:
        - zabbix-agent

    - role: 000-base-003-puppet
      tags:
        - puppet-agent

    - role: 001-infra-002-elastic
      tags:
        - elastic
      vars:
        - elastic_stack_version: 7.9.2
        - elasticsearch: true
        - cluster_name: private-cloud-elasticsearch
        - node_name: node01.es.freedom.org
        - cluster_hosts: [node01.es.freedom.org, node02.es.freedom.org, node03.es.freedom.org]
        - minimum_cluster_nodes: 2


- name: elasticsearch host node02.es.freedom.org
  hosts: node02.es.freedom.org
  user: root
  roles:
    - role: 000-base-000-common
      tags:
        - common

    - role: 000-base-001-consul
      tags:
        - consul-agent
      vars:
        consul_template_role: True
        consul_agent_role: True
        consul_agent_items:
          services:
            - name: elasticsearch-db
              port: 9200
            - name: elasticsearch-transport
              port: 9300
            - name: consul-agent
              port: 8500

    - role: 000-base-002-zabbix
      tags:
        - zabbix-agent

    - role: 000-base-003-puppet
      tags:
        - puppet-agent

    - role: 001-infra-002-elastic
      tags:
        - elastic
      vars:
        - elastic_stack_version: 7.9.2
        - elasticsearch: true
        - cluster_name: private-cloud-elasticsearch
        - node_name: node02.es.freedom.org
        - cluster_hosts: [node01.es.freedom.org, node02.es.freedom.org, node03.es.freedom.org]
        - minimum_cluster_nodes: 2


- name: elasticsearch host node03.es.freedom.org
  hosts: node03.es.freedom.org
  user: root
  roles:
    - role: 000-base-000-common
      tags:
        - common

    - role: 000-base-001-consul
      tags:
        - consul-agent
      vars:
        consul_template_role: True
        consul_agent_role: True
        consul_agent_items:
          services:
            - name: elasticsearch-db
              port: 9200
            - name: elasticsearch-transport
              port: 9300
            - name: consul-agent
              port: 8500

    - role: 000-base-002-zabbix
      tags:
        - zabbix-agent

    - role: 000-base-003-puppet
      tags:
        - puppet-agent

    - role: 001-infra-002-elastic
      tags:
        - elastic
      vars:
        - elastic_stack_version: 7.9.2
        - elasticsearch: true
        - cluster_name: private-cloud-elasticsearch
        - node_name: node03.es.freedom.org
        - cluster_hosts: [node01.es.freedom.org, node02.es.freedom.org, node03.es.freedom.org]
        - minimum_cluster_nodes: 2