---
- name: install prometheus
  hosts: prometheus.freedom.org
  user: root
  roles:
    - role: 000-base-000-common
      tags: common

    - role: 000-base-001-consul
      tags: consul-agent
      vars:
        consul_agent_role: true
        consul_template_role: true
        consul_agent_items:
          services:
            - { name: prometheus, port: 9090 }
            - { name: alertmanager, port: 9093 }
            - { name: pushgateway, port: 9091 }
            - { name: node-exporter, port: 9100 }
            - { name: grafana, port: 3000 }
            - { name: consul-agent, port: 8500 }

    - role: 000-base-002-zabbix
      tags: zabbix-agent

    - role: 000-base-003-puppet
      tags: puppet-agent

    - role: 000-base-010-node_exporter
      tags: node_exporter

    - role: 001-infra-011-prometheus
      tags:
        - prometheus
        - prom

    - role: 001-infra-012-alertmanager
      tags:
        - alertmanager
        - am

    - role: 001-infra-013-pushgateway
      tags:
        - pushgateway
        - pg

    - role: 001-infra-014-grafana
      tags:
        - grafana