---
- name: deploy bind master
  hosts: 192.168.2.250
  user: root
  roles:
    - role: 000-base-000-common
      tags: common
      vars:
        - common_local_dns: False
        - common_repo_type: "not_katello"

    - role: 000-base-001-consul
      tags: consul-agent
      vars:
        consul_agent_role: True
        consul_agent_items:
          services:
            - { name: consul-agent, port: 8500 }
            - { name: node-exporter, port: 9100 }
            - { name: zabbix-agent,  port: 10050 }
            - { name: bind, port: 53 }

    - role: 001-infra-001-bind
      tags:
        - dns
        - bind
      vars:
        - bind_master_role: true