---
- name: deploy haproxy
  hosts: haproxy.freedom.org
  user: root
  roles:
    - role: 000-base-000-common
      tags: common

    - role: 000-base-001-consul
      tags: consul-agent
      vars:
        consul_agent_role: true
        consul_agent_items:
          services:
            - { name: hubernetes-apiserver, port: 6443 }
            - { name: hubernetes-ingress-http, port: 32080 }
            - { name: hubernetes-ingress-https, port: 32443 }
            - { name: consul-agent, port: 8500 }

    - role: 000-base-003-puppet
      tags:
        - puppet

    - role: 001-infra-001-bind
      tags: dns
      vars:
        - bind_slave_role: true

    - role: 001-infra-019-haproxy
      tags:
        - haproxy