---
- name: deploy nfs server
  hosts: nfs.freedom.org
  user: root
  roles:
    - role: 000-base-000-common
      tags: common

    - role: 000-base-001-consul
      tags: consul
      vars:
        consul_agent_role: True
        consul_agent_items:
          services:
            - { name: consul-agent, port: 8500 }
            - { name: node-exporter, port: 9100 }
            - { name: zabbix-agent,  port: 10050 }
            - { name: nfs, port: 2049 }

    - role: 000-base-010-node-exporter
      tags:
        - node_exporter

    - role: 001-infra-005-nginx
      tags: nginx
      vars:
        - nginx_roles:
            - file-server

    - role: 001-infra-024-nfs
      tags:
        - nfs
      vars:
        - nfs_app: kubernetes