---
- name: deploy foreman
  hosts: localhost
  user: root
  roles:
    - role: 000-base-000-common
      tags: common
      vars:
        - common_local_dns: false
        - common_selinux_state: disabled

    - role: 001-infra-001-bind
      tags: dns
      vars:
        - bind_master_role: true

    - role: 001-infra-015-vsftpd
      tags: vsftpd

    - role: 001-infra-016-dhcp
      tags: dhcp

    - role: 000-base-001-consul
      tags: consul
      vars:
        consul_server_role: True
        consul_template_role: True

    - role: 001-infra-017-mysql
      tags: mysql