---
- name: init k8s master nodes
  hosts: master01.k8s.freedom.org
  user: root
  roles:
    - role: 001-infra-023-calico
      tags:
        - calico

    - role: 001-infra-021-helm
      tags:
        - helm

    - role: 001-infra-022-ingress-nginx
      tags:
        - ingress-nginx