---
- name: deploy harbor
  hosts: harbor.freedom.org
  user: root
  roles:
    - role: 000-base-000-common
      tags: common

    - role: 000-base-001-consul
      tags: consul-agent
      vars:
        consul_agent_role: True
        consul_agent_items:
          services:
            - { name: harbor, port: 80 }
            - { name: consul-agent, port: 8500 }
            - { name: node-exporter, port: 9100 }

    - role: 000-base-002-fluentd
      tags: fluentd

    - role: 000-base-003-puppet
      tags:
        - puppet

    - role: 000-base-010-node_exporter
      tags:
        - node_exporter

    - role: 000-base-005-docker
      tags: docker

    - role: 000-base-006-docker_images
      tags: docker_images
      vars:
        - docker_images_role: harbor

    - role: 001-infra-018-zabbix
      tags: zabbix

    - role: 001-infra-010-harbor
      tags: harbor