---
- name: deploy harbor
  hosts: harbor.freedom.org
  user: root
  roles:
    - role: 000-base-000-common
      tags: common

    - role: 000-base-001-consul
      tags: consul
      vars:
        consul_agent_role: True

    - role: 000-base-002-fluentd
      tags: fluentd

    - role: 000-base-005-docker
      tags: docker

    - role: 000-base-006-docker_images
      tags: docker_images
      vars:
        - docker_images_pull: true
        - docker_images_push: true

    - role: 001-infra-010-harbor
      tags: harbor