---
- name: deploy consul server
  hosts: node01.consul.freedom.org
  user: root
  roles:
    - role: 000-base-000-common
      tags: common

    - role: 000-base-001-consul
      tags: consul-server
      vars:
        consul_server_role: True


- name: deploy consul server
  hosts: node02.consul.freedom.org
  user: root
  roles:
    - role: 000-base-000-common
      tags: common

    - role: 000-base-001-consul
      tags: consul-server
      vars:
        consul_server_role: True


- name: deploy consul server
  hosts: node03.consul.freedom.org
  user: root
  roles:
    - role: 000-base-000-common
      tags: common

    - role: 000-base-001-consul
      tags: consul-server
      vars:
        consul_server_role: True