---
- name: deploy foreman
  hosts: localhost
  user: root
  roles:
    - role: 000-base-000-common
      tags: common

    - role: 000-base-001-consul
      tags: consul
      vars:
        consul_agent_role: True
        consul_agent_items:
          services:
            - { name: foreman, port: 8443 }
            - { name: consul-agent, port: 8500 }
            - { name: node-exporter, port: 9100 }
        consul_template_role: True

    - role: 001-infra-015-vsftpd
      tags: vsftpd

    - role: 000-base-010-node-exporter
      tags:
        - node_exporter