---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: storageclass-rbd-infra
  namespace: kube-system


---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: storageclass-rbd-infra
  namespace: kube-system
rules:
  - apiGroups: [""]
    resources: ["persistentvolumes"]
    verbs: ["get", "list", "watch", "create", "delete"]
  - apiGroups: [""]
    resources: ["persistentvolumeclaims"]
    verbs: ["get", "list", "watch", "update"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["storageclasses"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create", "update", "patch"]
  - apiGroups: [""]
    resources: ["services"]
    resourceNames: ["kube-dns","coredns"]
    verbs: ["list", "get"]


---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: storageclass-rbd-infra
  namespace: kube-system
subjects:
  - kind: ServiceAccount
    name: storageclass-rbd-infra
    namespace: kube-system
roleRef:
  kind: ClusterRole
  name: storageclass-rbd-infra
  apiGroup: rbac.authorization.k8s.io


---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: storageclass-rbd-infra
  namespace: kube-system
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get"]
- apiGroups: [""]
  resources: ["endpoints"]
  verbs: ["get", "list", "watch", "create", "update", "patch"]


---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: storageclass-rbd-infra
  namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: storageclass-rbd-infra
subjects:
  - kind: ServiceAccount
    name: storageclass-rbd-infra
    namespace: kube-system



---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: storageclass-rbd-infra
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app: storageclass-rbd-infra
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: storageclass-rbd-infra
    spec:
      containers:
      - name: storageclass-rbd-infra
        image: harbor.freedom.org/quay.io/rbd-provisioner:v2.1.1-k8s1.11
        env:
        - name: PROVISIONER_NAME
          value: ceph.com/storageclass-rbd-infra
      serviceAccount: storageclass-rbd-infra



---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: storageclass-rbd-infra
  namespace: kube-system
provisioner: ceph.com/storageclass-rbd-infra
parameters:
  monitors: node01.ceph.freedom.org:6789, node02.ceph.freedom.org:6789, node03.ceph.freedom.org:6789
  adminId: admin
  adminSecretName: storageclass-rbd-secret-infra
  adminSecretNamespace: kube-system
  pool: kubernetes-datastorage-rbd-infra
  userId: admin
  userSecretName: storageclass-rbd-secret-infra
  fsType: xfs
  imageFormat: "2"
  imageFeatures: "layering"
allowVolumeExpansion: true
reclaimPolicy: Retain


---
apiVersion: v1
kind: Secret
metadata:
  name: storageclass-rbd-secret-infra
  namespace: kube-system
type: "kubernetes.io/rbd"
data:
  key: QVFDbnlWNWhoMFpBRWhBQUVsL3AyWStkbGRpRzFucDJrUG0wbkE9PQ==