---
- name: deploy haproxy
  hosts: haproxy.freedom.org
  user: root
  roles:
    - role: 000-base-000-common
      tags: common

    - role: 001-infra-001-bind
      tags: dns
      vars:
        - bind_slave_role: true

    - role: 001-infra-019-haproxy
      tags:
        - haproxy