---
- name: init hosts
  hosts: "{{ hosts }}"
  user: root
  roles:
    - role: 000-base-000-common
      tags:
        - common

    - role: 001-infra-018-zabbix
      tags: zabbix

    - role: 000-base-010-node-exporter
      tags:
        - node-exporter