---
# 只能针对没有业务部署的主机，不可针对k8s主机主机执行，因为像consul-agent部署是用容器的daemonset模式部署。
- name: init hosts
  hosts: "{{ hosts }}"
  user: root
  roles:
    - role: 000-base-000-common
      tags:
        - common

    - role: 000-base-001-consul
      tags:
        - consul-agent
      vars:
        consul_template_role: True
        consul_agent_role: True
        consul_agent_items:
          services:
            - name: consul-agent
              port: 8500

    - role: 000-base-002-zabbix
      tags:
        - zabbix-agent

    - role: 000-base-003-puppet
      tags:
        - puppet-agent