# 默认认为k8s主机，此时会禁止swap。
is_k8s_host: false
is_redis_host: false
is_dns_server: false

common_local_file: /etc/rc.d/common.local
redis_local_file: /etc/rc.d/redis.local

# 此路由是打通虚拟机到容器内部的路由，这个是解决consul-server部署在容器中，而虚拟机
# consul-agent与consul-server通信时上报服务不成功的问题，因为consul-agent拿到的是
# pod ip，此路由只能写一个k8s主机地址，轻型流量应用是可以的。
# 指定网卡名称是因为主机上有多个网卡，默认为ens192。
static_route_nic: ens192

k8s_master01_ip: 192.168.2.1
k8s_pod_network: 10.244.0.0
k8s_pod_netmask: 16