---
- name: install cilium and hubble pkg
  unarchive:
    src: "{{ item.src }}"
    dest: /usr/local/bin
    mode: "0755"
    remote_src: yes
  with_items:
    - {src: "{{cilium_pkg_url }}" }
    - {src: "{{cilium_hubble_pkg_url }}" }

- name: install cilium and enable hubble
  shell: |
    cilium install
    cilium hubble enable --ui
  ignore_errors: yes
  register: cilium_install_result

- name: show install cilium log
  debug:
    msg:
      - "{{ cilium_install_result.stdout_lines }}"
      - "{{ cilium_install_result.stderr_lines }}"

- name: show cilium status
  shell: cilium status
  ignore_errors: yes
  register: cilium_status_result

- name: show install cilium status log
  debug:
    msg:
      - "{{ cilium_status_result.stdout_lines }}"
      - "{{ cilium_status_result.stderr_lines }}"

# 取消service，因为hubble-ui是以容器运行，所以不需要配置，访问hubble-ui只需要配置ingress即可。
#- name: generate hubble service
#  template:
#    src: "{{ item.src }}"
#    dest: "{{ systemd_conf_dir }}/{{ item.dest }}"
#  with_items:
#    - { src: hubble.service.j2, dest: hubble.service }
#    - { src: hubble-ui.service.j2, dest: hubble-ui.service }
#  notify:
#    - systemctl-daemon-reload
#    - restart-hubble
#    - restart-hubble-ui
