---
- name: install cilium and hubble pkg
  unarchive:
    src: "{{ item.src }}"
    dest: /usr/local/bin
    mode: "0755"
    remote_src: yes
  with_items:
    - {src: "{{cilium_pkg_url }}" }
    - {src: "{{cilium_hubble_pkg_url }}" }

- name: install cilium and enable hubble
  shell: |
    cilium install
    cilium hubble enable --ui
  ignore_errors: yes
  register: cilium_install_result

- name: show install cilium log
  debug:
    msg:
      - "{{ cilium_install_result.stdout_lines }}"
      - "{{ cilium_install_result.stderr_lines }}"

- name: show cilium status
  shell: cilium status
  ignore_errors: yes
  register: cilium_status_result

- name: show install cilium status log
  debug:
    msg:
      - "{{ cilium_status_result.stdout_lines }}"
      - "{{ cilium_status_result.stderr_lines }}"