- name: systemctl-daemon-reload
  systemd:
    daemon_reload: yes

- name: enable-alertmanager
  service:
    name: alertmanager
    enabled: yes

- name: restart-alertmanager
  service:
    name: alertmanager
    state: restarted
    enabled: yes