---
- name: systemctl-daemon-reload
  systemd:
    daemon_reload: yes

- name: restart kubelet
  service:
    name: kubelet
    state: restarted
    enabled: yes

- name: restart-network
  service:
    name: network
    state: restarted
    enabled: yes