---
consul_datacenter: default
consul_bootstrap_expect: 2
consul_domain: freedom.org

consul_ver: 1.8.0
consul_template_ver: 0.25.1

consul_agent_role: False
consul_server_role: False
consul_template_role: False

consul_agent_items:
  services:
    - { name: consul-agent,  port: 8500 }
    - { name: node-exporter, port: 9100 }
    - { name: zabbix-agent,  port: 10050 }

consul_servers:
  - node01.consul.freedom.org
  - node02.consul.freedom.org
  - node03.consul.freedom.org

consul_agent_dir: /etc/consul-agent
consul_agent_log_dir: "{{ consul_agent_dir }}/log"
consul_agent_data_dir: "{{ consul_agent_dir }}/data"
consul_agent_config_dir: "{{ consul_agent_dir }}/conf"
consul_agent_script_dir: "{{ consul_agent_dir }}/scripts"
consul_agent_log_file: "{{ consul_agent_log_dir }}/consul-agent.log"
consul_agent_pid_file: "{{ consul_agent_data_dir }}/consul-agent.pid"

consul_template_dir: /etc/consul-template
consul_template_data_dir: "{{ consul_template_dir }}/data"
consul_template_config_dir: "{{ consul_template_dir }}/conf"
consul_template_pid_file: "{{ consul_template_data_dir }}/consul-template.pid"
consul_template_service: "default"

consul_server_dir: /etc/consul-server
consul_server_log_dir: "{{ consul_server_dir }}/log"
consul_server_data_dir: "{{ consul_server_dir }}/data"
consul_server_config_dir: "{{ consul_server_dir }}/conf"
consul_server_log_file: "{{ consul_server_log_dir }}/consul-server.log"
consul_server_pid_file: "{{ consul_server_log_dir }}/consul-server.pid"