---
consul_datacenter: vm
consul_bootstrap_expect: 1
consul_domain: freedom.org

#consul_ver: 1.8.0
#consul_template_ver: 0.25.1
#
#consul_agent_role: False
#consul_server_role: False
#consul_template_role: False
#
#consul_agent_items:
#  services:
#    - { name: consul-agent, port: 8500 }
#
## consul-server使用ds部署在容器中，其服务端口全部原始映射到宿主机，然后使用haproxy进行转发，
##  所以对k8s集群外来说其ip地址是一个，以下是consul server部署在容器中的变量配置。
##consul_servers:
##  - consul.freedom.org
#
## 以下是虚拟机部署三台consul server变量配置示例。
#consul_servers:
#  - server01.consul.freedom.org
#  - server02.consul.freedom.org
#  - server03.consul.freedom.org
#
#consul_agent_dir: /etc/consul-agent
#consul_agent_log_dir: "{{ consul_agent_dir }}/log"
#consul_agent_data_dir: "{{ consul_agent_dir }}/data"
#consul_agent_config_dir: "{{ consul_agent_dir }}/conf"
#consul_agent_script_dir: "{{ consul_agent_dir }}/scripts"
#consul_agent_log_file: "{{ consul_agent_log_dir }}/consul-agent.log"
#consul_agent_pid_file: "{{ consul_agent_data_dir }}/consul-agent.pid"
#
#consul_template_dir: /etc/consul-template
#consul_template_data_dir: "{{ consul_template_dir }}/data"
#consul_template_config_dir: "{{ consul_template_dir }}/conf"
#consul_template_pid_file: "{{ consul_template_data_dir }}/consul-template.pid"
#
#consul_server_dir: /etc/consul-server
#consul_server_log_dir: "{{ consul_server_dir }}/log"
#consul_server_data_dir: "{{ consul_server_dir }}/data"
#consul_server_config_dir: "{{ consul_server_dir }}/conf"
#consul_server_log_file: "{{ consul_server_log_dir }}/consul-server.log"
#consul_server_pid_file: "{{ consul_server_log_dir }}/consul-server.pid"