---
- name: disable swap in /etc/fstab
  replace:
    path: /etc/fstab
    regexp: '(^/dev/mapper/centos-swap.*)'
    replace: '#\1'

- name: disable swap
  shell: swapoff -a

- name: set sysctl configurations to k8s hosts.
  sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    sysctl_set: yes
    reload: yes
    sysctl_file: /etc/sysctl.d/k8s.conf
  with_items:
    - { name: 'net.bridge.bridge-nf-call-ip6tables', value: 1 }
    - { name: 'net.bridge.bridge-nf-call-iptables', value: 1 }
    - { name: 'net.ipv4.ip_forward', value: 1 }
  ignore_errors: yes

- name: install k8s packages
  yum:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - tcl
      - openssl-devel
      - zlib-devel
      - docker-1.13.1-108.git4ef4b30.el7.centos.x86_64
      - docker-client-1.13.1-108.git4ef4b30.el7.centos.x86_64
      - docker-common-1.13.1-108.git4ef4b30.el7.centos.x86_64
      - kubeadm-1.16.2-0.x86_64
      - kubectl-1.16.2-0.x86_64
      - kubelet-1.16.2-0.x86_64
      - kubernetes-cni-0.7.5-0.x86_64
  notify: restart kubelet

