---
- name: '使用内网DNS'
  template:
    src: resolv.conf.j2
    dest: /etc/resolv.conf
  when: not is_dns_server

- name: delete origin repo files
  file:
    path: "/etc/yum.repos.d/{{ item }}"
    state: absent
  with_items:
    - CentOS-Base.repo
    - CentOS-CR.repo
    - CentOS-Debuginfo.repo
    - CentOS-fasttrack.repo
    - CentOS-Media.repo
    - CentOS-Sources.repo
    - CentOS-Vault.repo

- name: copy common repo files
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: "0644"
  with_items:
    - { src: "repos/centos-{{ ansible_distribution_major_version }}.repo", dest: /etc/yum.repos.d/centos.repo }
    - { src: "repos/epel-{{ ansible_distribution_major_version }}.repo", dest: /etc/yum.repos.d/epel.repo }
    - { src: "repos/kubernetes-{{ ansible_distribution_major_version }}.repo", dest: /etc/yum.repos.d/kubernetes.repo }
    - { src: "repos/zabbix-4.0-{{ ansible_distribution_major_version }}.repo", dest: /etc/yum.repos.d/zabbix.repo }
    - { src: "repos/ceph-mimic-{{ ansible_distribution_major_version }}.repo", dest: /etc/yum.repos.d/ceph.repo }
    - { src: "repos/docker-ce-{{ ansible_distribution_major_version }}.repo", dest: /etc/yum.repos.d/docker-ce-7.repo }
  when: ansible_distribution == "CentOS" or ansible_distribution == "RedHat"


# 增加虚拟机到k8s pod的路由，其网段及k8s的worker主机要根据实际情况改。
- name: create /etc/sysconfig/network-scripts/route-{{ static_route_nic }}
  blockinfile:
    path: /etc/sysconfig/network-scripts/route-{{ static_route_nic }}
    create: yes
    block: |
      {{ k8s_pod_network }}/{{ k8s_pod_netmask }} via {{ k8s_master01_ip }}
  notify:
    - restart-network

- name: modify PS1
  blockinfile:
    path: /etc/profile
    block: |
      if [ $UID -eq 0 ]; then
          export PS1="[\u@\H \[\e[34m\]\w\[\e[m\] \[\e[33m\]\A\[\e[m\]]# \#> "
      else
          export PS1="[\u@\H \[\e[34m\]\w\[\e[m\] \[\e[33m\]\A\[\e[m\]]$ \#> "
      fi

- name: disable iptables
  shell: iptables -F && iptables --list -n
  register: disable_iptables

- name: show disable iptables
  debug: var=disable_iptables.stdout_lines verbosity=0

- name: disable firewalld
  service:
    name: firewalld
    state: stopped
    enabled: no

- name: disable selinux
  selinux:
    state: disabled

- name: copy vimrc
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
    - { src: vimrc, dest: /root/.vimrc }
    - { src: vimrc, dest: "/{{ common_user }}/.vimrc" }

- name: install common packages
  yum:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - tcl
      - openssl-devel
      - zlib-devel
      - lrzsz
      - tree
      - nc
      - telnet

- name: unlimit the system limitations
  shell: ulimit -SHn 65535 && ulimit -n

- name: set unlimitations in the limits.conf file
  lineinfile:
    path: /etc/security/limits.conf
    state: present
    line: "{{ item.name }}"
  with_items:
    - { name: '* soft nofile 65536'}
    - { name: '* hard nofile 131072'}
    - { name: '* soft nproc 65535'}
    - { name: '* hard nproc 65535'}
