---
- name: configurate dns
  template:
    src:  resolv.conf.j2
    dest: /etc/resolv.conf
  when: common_local_dns

- name: modify PS1
  blockinfile:
    path: /etc/profile
    block: |
      if [ $UID -eq 0 ]; then
          export PS1="[\u@\H \[\e[34m\]\w\[\e[m\] \[\e[33m\]\A\[\e[m\]]# \#> "
      else
          export PS1="[\u@\H \[\e[34m\]\w\[\e[m\] \[\e[33m\]\A\[\e[m\]]$ \#> "
      fi

- name: disable iptables
  shell: iptables -F && iptables --list -n
  register: disable_iptables

- name: show disable iptables
  debug: var=disable_iptables.stdout_lines verbosity=0

- name: disable firewalld
  service:
    name: firewalld
    state: stopped
    enabled: no

- name: disable selinux
  selinux:
    state: "{{ common_selinux_state }}"

- name: copy vimrc
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
    - { src: vimrc, dest: /root/.vimrc }
    - { src: vimrc, dest: "/{{ common_user }}/.vimrc" }

- name: unlimit the system limitations
  shell: ulimit -SHn 65535 && ulimit -n

- name: set unlimitations in the limits.conf file
  lineinfile:
    path: /etc/security/limits.conf
    state: present
    line: "{{ item.name }}"
  with_items:
    - { name: '* soft nofile 65536'}
    - { name: '* hard nofile 131072'}
    - { name: '* soft nproc 65535'}
    - { name: '* hard nproc 65535'}
