---
- name: delete original repo files
  file:
    path: "/etc/yum.repos.d/{{ item }}"
    state: absent
  with_items:
    - CentOS-Base.repo
    - CentOS-CR.repo
    - CentOS-Debuginfo.repo
    - CentOS-fasttrack.repo
    - CentOS-Media.repo
    - CentOS-Sources.repo
    - CentOS-Vault.repo

- name: copy common repo files
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: "0644"
  with_items:
    - { src: "el{{ ansible_distribution_major_version }}/{{ repo_type }}/CentOS-Base.repo", dest: /etc/yum.repos.d/CentOS-Base.repo }
    - { src: "el{{ ansible_distribution_major_version }}/{{ repo_type }}/CentOS-CR.repo", dest: /etc/yum.repos.d/CentOS-CR.repo }
    - { src: "el{{ ansible_distribution_major_version }}/{{ repo_type }}/CentOS-Debuginfo.repo", dest: /etc/yum.repos.d/CentOS-Debuginfo.repo }
    - { src: "el{{ ansible_distribution_major_version }}/{{ repo_type }}/CentOS-fasttrack.repo", dest: /etc/yum.repos.d/CentOS-fasttrack.repo }
    - { src: "el{{ ansible_distribution_major_version }}/{{ repo_type }}/CentOS-Media.repo", dest: /etc/yum.repos.d/CentOS-Media.repo }
    - { src: "el{{ ansible_distribution_major_version }}/{{ repo_type }}/CentOS-Sources.repo", dest: /etc/yum.repos.d/CentOS-Sources.repo }
    - { src: "el{{ ansible_distribution_major_version }}/{{ repo_type }}/CentOS-Vault.repo", dest: /etc/yum.repos.d/CentOS-Vault.repo }
    - { src: "el{{ ansible_distribution_major_version }}/{{ repo_type }}/epel.repo", dest: /etc/yum.repos.d/epel.repo }

- name: modify PS1
  blockinfile:
    path: /etc/profile
    block: |
      if [ $UID -eq 0 ]; then
          export PS1="[\u@\H \[\e[34m\]\w\[\e[m\] \[\e[33m\]\A\[\e[m\]]# \#> "
      else
          export PS1="[\u@\H \[\e[34m\]\w\[\e[m\] \[\e[33m\]\A\[\e[m\]]$ \#> "
      fi

- name: disable iptables
  shell: iptables -F && iptables --list -n
  register: disable_iptables

- name: show disable iptables
  debug: var=disable_iptables.stdout_lines verbosity=0

- name: disable firewalld
  service:
    name: firewalld
    state: stopped
    enabled: no

- name: disable selinux
  selinux:
    state: disabled

- name: copy vimrc
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
    - { src: vimrc, dest: /root/.vimrc }
    - { src: vimrc, dest: "/{{ common_user }}/.vimrc" }

- name: install common packages
  yum:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - tcl
      - openssl-devel
      - zlib-devel
      - lrzsz
      - tree
      - nc
      - telnet

- name: unlimit the system limitations
  shell: ulimit -SHn 65535 && ulimit -n

- name: set unlimitations in the limits.conf file
  lineinfile:
    path: /etc/security/limits.conf
    state: present
    line: "{{ item.name }}"
  with_items:
    - { name: '* soft nofile 65536'}
    - { name: '* hard nofile 131072'}
    - { name: '* soft nproc 65535'}
    - { name: '* hard nproc 65535'}
