---
- name: copy tsinghua repo files
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: "0644"
  with_items:
    - { src: "el{{ ansible_distribution_major_version }}-repos/{{ common_repo_type }}/CentOS-Base.repo", dest: /etc/yum.repos.d/CentOS-Base.repo }
    - { src: "el{{ ansible_distribution_major_version }}-repos/{{ common_repo_type }}/CentOS-CR.repo", dest: /etc/yum.repos.d/CentOS-CR.repo }
    - { src: "el{{ ansible_distribution_major_version }}-repos/{{ common_repo_type }}/CentOS-Debuginfo.repo", dest: /etc/yum.repos.d/CentOS-Debuginfo.repo }
    - { src: "el{{ ansible_distribution_major_version }}-repos/{{ common_repo_type }}/CentOS-fasttrack.repo", dest: /etc/yum.repos.d/CentOS-fasttrack.repo }
    - { src: "el{{ ansible_distribution_major_version }}-repos/{{ common_repo_type }}/CentOS-Media.repo", dest: /etc/yum.repos.d/CentOS-Media.repo }
    - { src: "el{{ ansible_distribution_major_version }}-repos/{{ common_repo_type }}/CentOS-Sources.repo", dest: /etc/yum.repos.d/CentOS-Sources.repo }
    - { src: "el{{ ansible_distribution_major_version }}-repos/{{ common_repo_type }}/CentOS-Vault.repo", dest: /etc/yum.repos.d/CentOS-Vault.repo }
    - { src: "el{{ ansible_distribution_major_version }}-repos/{{ common_repo_type }}/epel.repo", dest: /etc/yum.repos.d/epel.repo }

- name: install common packages
  yum:
    name: "{{ packages }}"
    state: present
  vars:
    packages: "{{ common_pkgs }}"

- name: install katello-ca-consumer-latest.noarch.rpm
  yum:
    name: "{{ item }}"
  loop:
    - subscription-manager
    - http://foreman.freedom.org/pub/katello-ca-consumer-latest.noarch.rpm

- block:
    - name: delete original repo files
      file:
        path: "/etc/yum.repos.d/{{ item }}"
        state: absent
      with_items:
        - CentOS-Base.repo
        - CentOS-CR.repo
        - CentOS-Debuginfo.repo
        - CentOS-fasttrack.repo
        - CentOS-Media.repo
        - CentOS-Sources.repo
        - CentOS-Vault.repo
        - epel.repo

    - name: subscribe yum repo
      shell: |
        subscription-manager register --force --org="{{ common_register_org }}" --activationkey="{{ common_register_activationkey }}"
  when: common_repo_type == "katello"