---
# 针对redis应用配置
- name: set net.core.somaxconn to 65535.
  sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    sysctl_set: yes
    reload: yes
    sysctl_file: "{{ redis_local_file }}"
  with_items:
    - { name: 'net.core.somaxconn', value: 65535 }
    - { name: 'vm.overcommit_memory', value: 1 }

- name: set transparent_hugepage to enabled
  shell: echo never > /sys/kernel/mm/transparent_hugepage/enabled

- name: create {{ redis_local_file }} file
  file:
    path: "{{ redis_local_file }}"
    state: touch
    owner: root
    group: root
    mode: 0755

- name: set transparent_hugepage to enabled at the system boot
  lineinfile:
    path: "{{ redis_local_file }}"
    state: present
    line: 'echo never > /sys/kernel/mm/transparent_hugepage/enabled'