---
# tasks file for consul-server
- name: create consul dir
  file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: '0755'
    recurse: yes
  with_items:
    - "{{ consul_server_dir }}"
    - "{{ consul_server_log_dir }}"
    - "{{ consul_server_data_dir }}"
    - "{{ consul_server_config_dir }}"

- name: install consul package
  unarchive:
    src: consul_{{ consul_ver }}_linux_amd64.zip
    dest: /usr/local/bin/
    mode: 0755
  notify: restart-consul-server

- name: copy systemd conf
  when: (ansible_distribution == "CentOS" or ansible_distribution == "RedHat") and ansible_distribution_major_version == "7"
  template:
    src: systemd/consul-server.service.j2
    dest: "{{ systemd_conf_dir }}/consul-server.service"
    mode: 0644

- name: systemctl-daemon-reload
  systemd:
    daemon_reload: yes

- name: generate config from consul server
  tags: generate-config
  template:
    lstrip_blocks: true
    src: server/consul-server.j2
    dest: "{{ consul_server_config_dir }}/consul-server.json"
    mode: 0644
  notify: restart-consul-server
