---
# tasks file for consul-template

- name: init consul-template dir 
  file: 
    path: "{{ item }}"
    state: directory 
    owner: root
    group: root
    mode: 0755
  with_items:
    - "{{ consul_template_dir }}"
    - "{{ consul_template_data_dir }}"
    - "{{ consul_template_config_dir }}"

- name: install consul-template package
  unarchive:
    src: consul-template_{{ consul_template_ver }}_linux_amd64.tgz
    dest: /usr/local/bin/
    mode: 0755
  notify: restart-consul-template

- name: copy systemd conf
  when: (ansible_distribution == "CentOS" or ansible_distribution == "RedHat") and ansible_distribution_major_version == "7"
  template:
    src: systemd/consul-template.service.j2
    dest: "{{ systemd_conf_dir }}/consul-template.service"
    mode: 0644

- name: systemctl-daemon-reload
  systemd:
    daemon_reload: yes

- name: generate consul template hcl
  include: template-{{ consul_template_service }}.yml