---
# 根据官网方式安装
#- name: import gpg key
#  shell: rpm --import https://packages.treasuredata.com/GPG-KEY-td-agent
#
#- name: config yum repoistroy
#  copy:
#    src: td.repo
#    dest: /etc/yum.repos.d/td.repo
#
#- name: install td-agent(fluentd) rpm
#  yum:
#    name: td-agent

- name: copy gpg key
  copy:
    src: GPG-KEY-td-agent
    dest: /etc/pki/rpm-gpg/GPG-KEY-td-agent

- name: import gpg key
  shell: rpm --import file:///etc/pki/rpm-gpg/GPG-KEY-td-agent

- name: copy td-agent(fluentd) rpm
  copy:
    src: "{{ fluentd_pkg }}"
    dest: "/usr/local/src/{{ fluentd_pkg }}"

- name: install td-agent(fluentd) rpm
  yum:
    name: "/usr/local/{{ fluentd_pkg }}"

- name: update td-agent running user to be root
  lineinfile:
    path: /usr/lib/systemd/system/td-agent.service
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    backrefs: yes
  with_items:
    - { regexp: "User=td-agent", line: "User=root" }
    - { regexp: "Group=td-agent", line: "Group=root" }
  notify:
    - systemctl-daemon-reload
    - restart-td-agent