---
# 这个方法是可以启动的。
- name: Restart elasticsearch.
  shell: |
    su - "{{ user_name }}" -c "(ps -ef | grep \"{{ elasticsearch_proc }}\" | grep -v grep | awk '{print $2}' | xargs kill -9 || echo '此程序未启动。') && {{ elasticsearch_bin }}"
  args:
    executable: /bin/bash

# 换一个方式，进行测试，从理论上来看，这和上面的没有区别，但是就是启动不了。
# 从启动日志来看，还是使用root，结果打脸了，是自己的方法不对，需要使用become和become_user来配合。
# 一测试，结果发现还是不行。
#- name: Restart elasticsearch.
#  shell: |
#    ps -ef | grep \"{{ elasticsearch_proc }}\" | grep -v grep | awk '{print $2}' | xargs kill -9 || echo '此程序未启动。'
#    {{ elasticsearch_bin }}
#  args:
#    executable: /bin/bash
#  become: true
#  become_user: "{{ user_name }}"
