---
# 官方地址：https://goharbor.io/docs

- name: copy ssl files
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
    - { src: freedom.org.crt, dest: /etc/ssl/certs/freedom.org.crt }
    - { src: freedom.org.key, dest: /etc/ssl/certs/freedom.org.key }

- name: create harbor data directory
  file:
    path: "{{ harbor_data_dir }}"
    state: directory

- name: download harbor installer package
  get_url:
    url: "{{ harbor_url }}"
    dest: "{{ harbor_pkg_file }}"

- name: delete harbor-online-installer old package
  file:
    path: "{{ harbor_pkg_dir }}"
    state: absent

- name: unarchive harbor package
  unarchive:
    src: "{{ harbor_pkg_file }}"
    dest: "{{ harbor_pkg_root_dir }}"
    remote_src: yes

- name: create harbor.yml file
  template:
    src: "{{ harbor_version }}/harbor.yml.tmpl.j2"
    dest: /usr/local/harbor/harbor.yml

# 每个版本的安装命令不一样。
- name: install harbor
  shell: cd /usr/local/harbor && ./install.sh --with-notary --with-trivy --with-chartmuseum
  register: install_harbor_status
  when: harbor_version == "v2.3.2"

- name: show install harbor status
  debug:
    var: install_harbor_status.stdout_lines

- name: chmod 755 /etc/rc.d/rc.local
  file:
    path: /etc/rc.d/rc.local
    mode: "0755"

- name: setup rc.local to start docker-compose on boot
  blockinfile:
    path: /etc/rc.d/rc.local
    block: |
      cd /usr/local/harbor && /usr/bin/docker-compose up -d