---
- name: systemctl-daemon-reload
  systemd:
    daemon_reload: yes

- name: restart-nginx
  service:
    name: nginx
    state: restarted
    enabled: yes

- name: start-nginx
  service:
    name: nginx
    state: started
    enabled: yes

- name: stop-nginx
  service:
    name: nginx
    state: stopped
    enabled: yes

- name: reload-nginx
  service:
    name: nginx
    state: reloaded
    enabled: yes