---
# https://github.com/helm/helm/releases
helm_version: v3.10.0
helm_pkg_url: "{{ file_server }}/kubernetes/helm/helm-{{ helm_version }}-linux-amd64.tar.gz"
helm_download_dir: /tmp
helm_bin_path: /usr/local/bin