---
- name: install ceph packages
  yum:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - ceph-common

# 理论来说，这下面的配置应该使用template实现，因个人数据中心只有一个集群，也很少变化，所以先用copy完成。
- name: copy ceph configuration files
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
    - { src: ceph.conf, dest: /etc/ceph/ceph.conf }
    - { src: ceph.client.admin.keyring, dest: /etc/ceph/ceph.client.admin.keyring }