---
- name: install puppet package
  yum:
    name: "{{ item }}"
    state: present
  loop:
    - puppet-agent

- name: generate puppet agent configuration file
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
    - { src: puppet-agent/puppet.conf.j2, dest: /etc/puppetlabs/puppet/puppet.conf }
  notify:
    - restart-puppet-agent