---
- name: generate redis standalone playbook
  hosts: localhost
  gather_facts: False

  tasks:
    - name: generate redis standalone playbook
      template:
        src: redis-standalone-template.yml.j2
        dest: "/tmp/0-{{ item.host }}-{{ item.redis_port }}.yml"
      loop:
        - {"host": 'redis.freedom.org', redis_version: "3.2.13", is_install_redis: false,  "redis_port": 20001, "redis_password": "hnwyrxaAh8Ctib2ggwj&tsjzhippvoak" }
        - {"host": 'redis.freedom.org', redis_version: "3.2.13", is_install_redis: false,  "redis_port": 20002, "redis_password": "d]beitzzbbpe5twnTlkrcjewuyqJstj8" }
        - {"host": 'redis.freedom.org', redis_version: "3.2.13", is_install_redis: false,  "redis_port": 20003, "redis_password": "zedi2tsymxzeWtxwxsybhjp~bqrFmrw7" }
        - {"host": 'redis.freedom.org', redis_version: "3.2.13", is_install_redis: false,  "redis_port": 20004, "redis_password": "exeuvjkca5x/xdaabzdh4mobgxapVAmq" }
        - {"host": 'redis.freedom.org', redis_version: "3.2.13", is_install_redis: false,  "redis_port": 20005, "redis_password": "f,sWcbhvlrLwlkvm69dinmgmfqqubkrq" }
        - {"host": 'redis.freedom.org', redis_version: "3.2.13", is_install_redis: false,  "redis_port": 20006, "redis_password": "tmrgwUholnq+fcbp9rKunvkbx6iglzsu" }
        - {"host": 'redis.freedom.org', redis_version: "3.2.13", is_install_redis: false,  "redis_port": 20007, "redis_password": "qdtvkGkuiywnYxsylk99sqjbuds]qdja" }
        - {"host": 'redis.freedom.org', redis_version: "3.2.13", is_install_redis: false,  "redis_port": 20008, "redis_password": "trtlsKGnbfmj4stzosisr1yzkzpaapt-" }
        - {"host": 'redis.freedom.org', redis_version: "3.2.13", is_install_redis: false,  "redis_port": 20009, "redis_password": "ajzEfdtvhpt0Y*orbvqftdbv9rswddix" }
        - {"host": 'redis.freedom.org', redis_version: "3.2.13", is_install_redis: false,  "redis_port": 20010, "redis_password": "Mibrsmggz6qfondegshke:uKms9nnvyv" }
        - {"host": 'redis.freedom.org', redis_version: "3.2.13", is_install_redis: false,  "redis_port": 20011, "redis_password": "kokgsbdlv3kuRwgxl-oRjxzfkb6zxuwj" }
        - {"host": 'redis.freedom.org', redis_version: "3.2.13", is_install_redis: false,  "redis_port": 20012, "redis_password": "gvg=vjhmjycLaucqtzoxcyw65cPpqeio" }