---
- name: generate redis cluster playbook
  hosts: localhost
  gather_facts: False

  tasks:
    - name: generate redis cluster playbook
      template:
        src: redis-cluster-template.yml.j2
        dest: "/tmp/0-{{ item.service_name }}.yml"

      with_items:
        - {
            service_name: 'drill-eshop-redis-cluster-global',
            redis_version: '3.2.13',
            redis_replicas: 1,
            instances: [
              {"host": '10.8.60.136', is_install_ruby: true,  is_install_gem_pkgs: true , redis_cluster_role: true, is_install_redis: true,  "redis_port": 10001, redis_password: '007' }
            ]
        }