---
# zabbix-agent和zabbix-agent2不要同时安装，默认安装zabbix-agent。

zabbix_version: 5.0

zabbix_server_role: False
zabbix_agent_role: True
zabbix_agent2_role: False

zabbix_server_pkgs:
  - "zabbix-server-mysql-{{ zabbix_version }}.*"
  - "zabbix-web-mysql-scl-{{ zabbix_version }}.*"
  - "zabbix-apache-conf-scl-{{ zabbix_version }}.*"

zabbix_agent_pkgs:
  - "zabbix-agent-{{ zabbix_version }}.*"

zabbix_agent2_pkgs:
  - "zabbix-agent2-{{ zabbix_version }}.*"

zabbix_server: "zabbix.freedom.org"
zabbix_active_server: "zabbix.freedom.org"

zabbix_db_host: localhost
zabbix_db_port: 3306
zabbix_db_name: zabbix
zabbix_db_username: zabbix
zabbix_db_password: Zabbix@123.com
