---
- name: Configure the kernel parameters
  sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    sysctl_set: yes
    reload: yes
    sysctl_file: "{{ elasticstack_sysctl_file }}"
  with_items:
    - { name: "vm.max_map_count", value: 655360 }


# 使用root账号调整系统参数，初始化已经配置过了。
#- name: Apply the limits and kernel settings.
#  shell: |
#    source /etc/profile
#    /sbin/sysctl -p "{{ elasticstack_sysctl_file }}"
#    ulimit -n 65535

- name: install elasticsearch {{ elasticstack_version }}
  yum:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - "{{ elasticstack_elasticsearch_pkg }}"

- name: config elasticsearch {{ elasticstack_version }}
  template:
    src: "{{ elasticstack_major_version }}/elasticsearch.yml.j2"
    dest: /etc/elasticsearch/elasticsearch.yml
  notify: restart-elasticsearch

- name: configurate elasticsearch users
  shell: |
    service elasticsearch restart

    cd /usr/share/elasticsearch/bin

    echo -e "{{ elasticstack_superuser_password }}\n{{ elasticstack_superuser_password }}" | ./elasticsearch-users useradd superuser
    ./elasticsearch-users roles -a superuser superuser
    service elasticsearch restart

    echo -e "y\n" | ./elasticsearch-setup-passwords auto

    curl -X PUT -H "Content-Type: application/json" -d '{"password": "{{ elasticstack_apm_system_password }}"}' -u superuser:"{{ elasticstack_superuser_password }}" \
    http://localhost:9200/_xpack/security/user/apm_system/_password

    curl -X PUT -H "Content-Type: application/json" -d '{"password": "{{ elasticstack_kibana_system_password }}"}' -u superuser:"{{ elasticstack_superuser_password }}" \
    http://localhost:9200/_xpack/security/user/kibana_system/_password

    curl -X PUT -H "Content-Type: application/json" -d '{"password": "{{ elasticstack_kibana_password }}"}' -u superuser:"{{ elasticstack_superuser_password }}" \
    http://localhost:9200/_xpack/security/user/kibana/_password

    curl -X PUT -H "Content-Type: application/json" -d '{"password": "{{ elasticstack_logstash_system_password }}"}' -u superuser:"{{ elasticstack_superuser_password }}" \
    http://localhost:9200/_xpack/security/user/logstash_system/_password

    curl -X PUT -H "Content-Type: application/json" -d '{"password": "{{ elasticstack_beats_system_password }}"}' -u superuser:"{{ elasticstack_superuser_password }}" \
    http://localhost:9200/_xpack/security/user/beats_system/_password

    curl -X PUT -H "Content-Type: application/json" -d '{"password": "{{ elasticstack_remote_monitoring_user_password }}"}' -u superuser:"{{ elasticstack_superuser_password }}" \
    http://localhost:9200/_xpack/security/user/remote_monitoring_user/_password

    curl -X PUT -H "Content-Type: application/json" -d '{"password": "{{ elasticstack_elastic_password }}"}' -u superuser:"{{ elasticstack_superuser_password }}" \
    http://localhost:9200/_xpack/security/user/elastic/_password

    service elasticsearch restart
  register: conf_es_users
  ignore_errors: yes

- name: show configurate elasticsearch users result (stdout)
  debug:
    var: conf_es_users.stdout_lines

- name: show configurate elasticsearch users result (stderr)
  debug:
    var: conf_es_users.stderr_lines