---
- name: Configure the kernel parameters
  blockinfile:
    path: "{{ elasticstack_sysctl_file }}"
    block: |
      {{ item.key }} = {{ item.value }}
    create: yes
  with_items:
    - { key: vm.max_map_count, value: 655360 }


# 使用root账号调整系统参数，初始化已经配置过了。
#- name: Apply the limits and kernel settings.
#  shell: |
#    source /etc/profile
#    /sbin/sysctl -p "{{ elasticstack_sysctl_file }}"
#    ulimit -n 65535

- name: install elasticsearch {{ elasticstack_version }}
  yum:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - "{{ elasticstack_elasticsearch_pkg }}"

- name: config elasticsearch {{ elasticstack_version }}
  template:
    src: "{{ elasticstack_major_version }}/elasticsearch.yml.j2"
    dest: /etc/elasticsearch/elasticsearch.yml
  notify: restart-elasticsearch