- name: install filebeat {{ elasticstack_version }}
  yum:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - "{{ elasticstack_filebeat_pkg }}"

- name: config filebeat {{ elasticstack_version }} for {{ elasticstack_client_type }}
  template:
    src: "{{ elasticstack_major_version }}/filebeat-{{ elasticstack_client_type }}.yml.j2"
    dest: /etc/filebeat/filebeat.yml
  when: elasticstack_client_type is defined
  notify: restart-filebeat

- name: config filebeat {{ elasticstack_version }}
  template:
    src: "{{ elasticstack_major_version }}/filebeat.yml.j2"
    dest: /etc/filebeat/filebeat.yml
  when: elasticstack_client_type is not defined
  notify: restart-filebeat