- name: install filebeat {{ elasticstack_version }}
  yum:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - "{{ elasticstack_filebeat_pkg }}"

- name: config filebeat {{ elasticstack_version }}
  template:
    src: "{{ elasticstack_major_version }}/filebeat.yml.j2"
    dest: /etc/filebeat/filebeat.yml
  notify: restart-filebeat