- name: install kibana {{ elasticstack_version }}
  yum:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - "{{ elasticstack_kibana_pkg }}"

- name: config kibana {{ elasticstack_version }}
  template:
    src: "{{ elasticstack_major_version }}/kibana.yml.j2"
    dest: /etc/kibana/kibana.yml
  notify: restart-kibana