# Setup/install tasks.
- include: common.yml

- include: elasticsearch.yml
  when: elasticstack_elasticsearch

- include: filebeat.yml
  when: elasticstack_filebeat

- include: kibana.yml
  when: elasticstack_kibana