---
- name: install kubeadm
  yum:
    name: "kubeadm-{{ docker_images_k8s_version }}"
    state: present

- name: copy the docker images list
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
    - { src: "{{ docker_images_list_file }}", dest: "{{ docker_images_list_file }}" }

- name: generate script
  template:
    src: docker_images.py.j2
    dest: docker_images.py

- name: pull and push docker images
  shell: |
    python docker_images.py -f "{{ docker_images_list_file }}" -a "pull"
    python docker_images.py -v "{{ docker_images_k8s_version }}" -a "pull"
    python docker_images.py -f "{{ docker_images_list_file }}" -a "push"
    python docker_images.py -v "{{ docker_images_k8s_version }}" -a "push"
  register: result

- name: show pull docker images stdout
  debug:
    msg: "{{ result.stdout_lines }}"

- name: show pull docker images stderr
  debug:
    msg: "{{ result.stdout_lines }}"