---
- name: unarchive node_exporter { node_exporter_version }}
  unarchive:
    src: files/node_exporter-1.3.1.linux-amd64.tar.gz
    dest: /usr/local/src

- name: install node_exporter {{ node_exporter_version }}
  copy:
    src: "/usr/local/src/{{ node_exporter_dir }}/node_exporter"
    dest: "{{ node_exporter_bin }}"
    mode: "0755"
    remote_src: yes

- name: create node_exporter service
  template:
    src: node-exporter.service.j2
    dest: "{{ systemd_conf_dir }}/node-exporter.service"
  notify:
    - systemctl-daemon-reload
    - enable-node-exporter
    - restart-node-exporter