---
- name: install node_exporter {{ node_exporter_version }}
  get_url:
    url: "{{ node_exporter_pkg }}"
    dest: "{{ node_exporter_bin }}"
    mode: "0755"

- name: create node_exporter service
  template:
    src: node-exporter.service.j2
    dest: "{{ systemd_conf_dir }}/node-exporter.service"
  notify:
    - systemctl-daemon-reload
    - enable-node-exporter
    - restart-node-exporter