---
- name: install zabbix_agent
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - zabbix-agent
    - zabbix-get
    - zabbix-sender

- name: update zabbix agentd config
  template:
    src: zabbix_agentd.conf.j2
    dest: /etc/zabbix/zabbix_agentd.conf
  notify: restart-zabbix-agent
