apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: prometheus
  namespace: prometheus
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
    - host: prometheus.ingress-nginx.freedom.org
      http:
        paths:
        - path: /
          backend:
            serviceName: prometheus
            servicePort: 9090