---
# defaults file for proxy
# haproxy配置负责转发有的规则，所以角色对外时，不需要额外变量。
haproxy_ctmpl: haproxy-ctmpl-static

#tcp_instances:
#  - listen_name: rancher
#    service_name: rancher-https
#    args:
#      - "bind 0.0.0.0:8443"
#      - "balance source"
#  - listen_name: zookeeper
#    service_name: zookeeper-client
#    args:
#      - "bind 0.0.0.0:2181"
#      - "balance source"


# 以下的http/https配置项默认值是针对playbook：deploy-haproxy-for-vm.yml。
http_instances:
  - service_name: prometheus                         # service_name，主机上报的consul service名称，进示渲染backend_name后端的主机。
    http_host_header: ^prometheus.freedom.org$          # 当前acl规则以hdr_reg(host)进行匹配。
    httpchk_method: GET                             # 七层检查方法。
    httpchk: "/"                                    # 七层检查方法，后面接url或其他参数
  - service_name: grafana
    http_host_header: ^grafana.freedom.org$
    httpchk_method: GET
    httpchk: "/"


https_instances:
  - service_name: prometheus                         # service_name，主机上报的consul service名称，进示渲染backend_name后端的主机。
    http_host_header: ^prometheus.freedom.org$          # 当前acl规则以hdr_reg(host)进行匹配。
    httpchk_method: GET                             # 七层检查方法。
    httpchk: "/"                                    # 七层检查方法，后面接url或其他参数
  - service_name: grafana
    http_host_header: ^grafana.freedom.org$
    httpchk_method: GET
    httpchk: "/"