---
# defaults file for proxy
# haproxy配置负责转发有的规则，所以角色对外时，不需要额外变量。
haproxy_ctmpl: haproxy-ctmpl

tcp_instances:
  - listen_name: rancher
    service_name: rancher-https
    args:
      - "bind 0.0.0.0:8443"
      - "balance source"
  - listen_name: zookeeper
    service_name: zookeeper-client
    args:
      - "bind 0.0.0.0:2181"
      - "balance source"

http_instances:
  - service_name: consul-ui                         # service_name，主机上报的consul service名称，进示渲染backend_name后端的主机。
    http_host_header: ^web.consul.freedom.org$          # 当前acl规则以hdr_reg(host)进行匹配。
    httpchk_method: GET                             # 七层检查方法。
    httpchk: "/"                                    # 七层检查方法，后面接url或其他参数
  - service_name: zabbix-web
    http_host_header: ^zabbix.freedom.org$
    httpchk_method: GET
    httpchk: "/"
  - service_name: registry
    http_host_header: ^registry.freedom.org$
    httpchk_method: GET
    httpchk: "/"
  - service_name: kibana
    http_host_header: ^kibana.freedom.org$
  - service_name: grafana
    http_host_header: ^grafana.freedom.org$
    httpchk_method: GET
    httpchk: "/"


https_instances:
  - service_name: harbor-k8s
    http_host_header: ^harbor-k8s.freedom.org$          # 多次测试，发现验证harbor时使用七层检查时，始终报错，最后使用四层。