---
- name: install dhcpd
  yum:
    name: "{{ item }}"
    state: present
  loop:
    - tftp-server
    - xinetd

- name: generate tftp file
  template:
    src: tftp.j2
    dest: /etc/xinetd.d/tftp
  notify:
    - restart-xinetd