---
- name: Configure the kernel parameters
  sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    sysctl_set: yes
    reload: yes
    sysctl_file: "{{ elastic_sysctl_file }}"
  with_items:
    - { name: "vm.max_map_count", value: 655360 }

# 系统重启后，elasticsearch启动超问题的解决方法。
- name: update systemd elasticsearch service
  lineinfile:
    path: /usr/lib/systemd/system/elasticsearch.service
    regexp: "{{item.regexp }}"
    line: "{{ item.line }}"
    insertafter: "{{ item.insertafter }}"
  with_items:
    - { regexp: '^RestartSec=', line: 'RestartSec=1s', insertafter: '^KillMode=' }
    - { regexp: '^Restart=', line: 'Restart=on-failure', insertafter: '^KillMode=' }
  notify:
    - systemctl-daemon-reload
    - restart-elasticsearch

- name: install elasticsearch {{ elastic_version }}
  yum:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - "{{ elastic_elasticsearch_pkg }}"

- name: config elasticsearch {{ elastic_version }}
  template:
    src: "{{ elastic_major_version }}/elasticsearch.yml.j2"
    dest: /etc/elasticsearch/elasticsearch.yml
  notify: restart-elasticsearch

- name: configurate elasticsearch users
  shell: |
    service elasticsearch restart

    cd /usr/share/elasticsearch/bin

    echo -e "{{ elastic_superuser_password }}\n{{ elastic_superuser_password }}" | ./elasticsearch-users useradd superuser
    ./elasticsearch-users roles -a superuser superuser
    service elasticsearch restart

    echo -e "y\n" | ./elasticsearch-setup-passwords auto

    curl -X PUT -H "Content-Type: application/json" -d '{"password": "{{ elastic_apm_system_password }}"}' -u superuser:"{{ elastic_superuser_password }}" \
    http://localhost:9200/_xpack/security/user/apm_system/_password

    curl -X PUT -H "Content-Type: application/json" -d '{"password": "{{ elastic_kibana_system_password }}"}' -u superuser:"{{ elastic_superuser_password }}" \
    http://localhost:9200/_xpack/security/user/kibana_system/_password

    curl -X PUT -H "Content-Type: application/json" -d '{"password": "{{ elastic_kibana_password }}"}' -u superuser:"{{ elastic_superuser_password }}" \
    http://localhost:9200/_xpack/security/user/kibana/_password

    curl -X PUT -H "Content-Type: application/json" -d '{"password": "{{ elastic_logstash_system_password }}"}' -u superuser:"{{ elastic_superuser_password }}" \
    http://localhost:9200/_xpack/security/user/logstash_system/_password

    curl -X PUT -H "Content-Type: application/json" -d '{"password": "{{ elastic_beats_system_password }}"}' -u superuser:"{{ elastic_superuser_password }}" \
    http://localhost:9200/_xpack/security/user/beats_system/_password

    curl -X PUT -H "Content-Type: application/json" -d '{"password": "{{ elastic_remote_monitoring_user_password }}"}' -u superuser:"{{ elastic_superuser_password }}" \
    http://localhost:9200/_xpack/security/user/remote_monitoring_user/_password

    curl -X PUT -H "Content-Type: application/json" -d '{"password": "{{ elastic_elastic_password }}"}' -u superuser:"{{ elastic_superuser_password }}" \
    http://localhost:9200/_xpack/security/user/elastic/_password

    service elasticsearch restart
  register: conf_es_users
  ignore_errors: yes

- name: show configurate elasticsearch users result (stdout)
  debug:
    var: conf_es_users.stdout_lines

- name: show configurate elasticsearch users result (stderr)
  debug:
    var: conf_es_users.stderr_lines