- name: install filebeat {{ elastic_version }}
  yum:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - "{{ elastic_filebeat_pkg }}"

- name: config filebeat {{ elastic_version }} for {{ elastic_client_type }}
  template:
    src: "{{ elastic_major_version }}/filebeat-{{ elastic_client_type }}.yml.j2"
    dest: /etc/filebeat/filebeat.yml
  when: elastic_client_type is defined
  notify: restart-filebeat

- name: config filebeat {{ elastic_version }}
  template:
    src: "{{ elastic_major_version }}/filebeat.yml.j2"
    dest: /etc/filebeat/filebeat.yml
  when: elastic_client_type is not defined
  notify: restart-filebeat