- name: Unarchive elk elasticsearch package.
  unarchive:
    src: "{{ elk_pkg_url }}"
    dest: "{{ elk_pkg_dest }}"
    remote_src: yes
    owner: "{{ elk_user }}"
    group: "{{ elk_user }}"


- name: Create the elk elasticsearch link.
  file:
    src: "{{ elk_pkg_dest }}/{{ elk_pkg }}"
    dest: "{{ elk_link_dir }}"
    state: link


- name: Configure the global environment.
  blockinfile:
    path: /etc/profile
    block: |
      PATH=$PATH:"{{ elk_link_dir }}/bin"
      export PATH