---
- name: restart-kubelet
  service:
    name: kubelet
    state: restarted
    enabled: yes

- name: restart-NetworkManager
  service:
    name: NetworkManager
    state: restarted
    enabled: yes