---
# elastic stack角色启用，默认为False。
elasticsearch: False
kibana: False
logstash: False
filebeat: False

# elastic stack公共变量
elastic_stack_version: 7.9.2
pkg_url: "ftp://foreman.freedom.org/pub/yum/elastic"
elasticsearch_pkg: "elasticsearch-{{ elastic_stack_version }}-x86_64.rpm"
kibana_pkg: "kibana-{{ elastic_stack_version }}-x86_64.rpm"
logstash_pkg: "logstash-{{ elastic_stack_version }}.rpm"
filebeat_pkg: "filebeat-{{ elastic_stack_version }}-x86_64.rpm"

# 以下为elasticsearch配置变量
cluster_name: elasticsearch
cluster_nodes: ""                       # 在写playbook时指定变量值即可。
sysctl_file: /etc/sysctl.d/100-elk.conf # 系统调优参数

# 以下为kibana配置变量
server_name: kibana.es.freedom.org
elasticsearch_hosts: ""