---
- name: systemctl-daemon-reload
  systemd:
    daemon_reload: yes

- name: reload-haproxy
  service:
    name: haproxy
    state: reloaded
    enabled: yes

- name: restart-haproxy
  service:
    name: haproxy
    state: restarted
    enabled: yes