---
- include: roles/000-base-000-common/handlers/main.yml

- include: roles/000-base-001-consul/handlers/main.yml

- name: restart-haproxy
  service:
    name: haproxy
    state: restarted
    enabled: yes

- name: reload-haproxy
  service:
    name: haproxy
    state: reloaded
    enabled: yes

- name: restart-rsyslog
  service:
    name: rsyslog
    state: restarted
    enabled: yes

- name: systemctl-enable-haproxy
  systemd:
    name: haproxy
    enabled: yes
