---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: elasticsearch-client
  namespace: elasticsearch
  labels:
    app: elasticsearch-client


---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: elasticsearch-client
  namespace: elasticsearch
  labels:
    app: elasticsearch-client
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: elasticsearch-client
subjects:
  - kind: ServiceAccount
    name: elasticsearch-client
    namespace: elasticsearch


---
kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: elasticsearch-client
  namespace: elasticsearch
  labels:
    component: elasticsearch
    role: client
spec:
  serviceName: elasticsearch-client
  replicas: 1
  selector:
    matchLabels:
      component: elasticsearch
      role: client
  template:
    metadata:
      labels:
        component: elasticsearch
        role: client
    spec:
      serviceAccountName: elasticsearch-client
      initContainers:
      - name: init-sysctl
        image: busybox:1.31.1
        command:
        - sysctl
        - -w
        - vm.max_map_count=262144
        securityContext:
          privileged: true
      containers:
      - name: elasticsearch-client
        image: harbor.freedom.org/elastic/elasticsearch:7.9.2
        env:
          - name: TZ
            value: Asia/Shanghai
          - name: "ES_JAVA_OPTS"
            value: "-Xms512m -Xmx512m"
          - name: "cluster.name"
            value: "elasticsearch"
          - name: "discovery.seed_hosts"        # 这里用服务发现
            value: "elasticsearch-master"
          - name: "node.master"
            value: "false"
          - name: "node.data"
            value: "false"
          - name: "node.ingest"
            value: "false"
          - name: "node.ml"
            value: "false"
          - name: "node.remote_cluster_client"  # 各个角色介绍：https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-node.html
            value: "false"
        resources:
          limits:
            cpu: 1
        ports:
          - name: http
            containerPort: 9200
        volumeMounts:
        - name: storage
          mountPath: /data
      volumes:
          - emptyDir:
              medium: ""
            name: storage


---
kind: Service
apiVersion: v1
metadata:
  name: elasticsearch-client
  namespace: elasticsearch
  labels:
    component: elasticsearch
    role: client
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    component: elasticsearch
    role: client
  ports:
    - name: http
      port: 9200
      protocol: TCP