---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: elasticsearch-data
  namespace: elasticsearch
  labels:
    app: elasticsearch-data


---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: elasticsearch-data
  namespace: elasticsearch
  labels:
    app: elasticsearch-data
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: elasticsearch-data
subjects:
  - kind: ServiceAccount
    name: elasticsearch-data
    namespace: elasticsearch


---
kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: elasticsearch-data
  namespace: elasticsearch
  labels:
    component: elasticsearch
    role: data
spec:
  serviceName: elasticsearch-data
  replicas: 3
  selector:
    matchLabels:
      component: elasticsearch
      role: data
  template:
    metadata:
      labels:
        component: elasticsearch
        role: data
    spec:
      serviceAccountName: elasticsearch-data
      initContainers:
        - name: init-sysctl
          image: harbor.freedom.org/docker.io/busybox:1.31.1
          command:
            - sysctl
            - -w
            - vm.max_map_count=262144
          securityContext:
            privileged: true
      containers:
        - name: elasticsearch-data
          image: harbor.freedom.org/elastic/elasticsearch:7.9.2
          imagePullPolicy: IfNotPresent
          env:
            - name: TZ
              value: Asia/Shanghai
            - name: "ES_JAVA_OPTS"
              value: "-Xms512m -Xmx512m"
            - name: "cluster.name"
              value: "elasticsearch"
            - name: "discovery.seed_hosts"        # 这里用服务发现
              value: "elasticsearch-master"
            - name: "node.master"
              value: "false"
            - name: "node.data"
              value: "true"
            - name: "node.ingest"
              value: "false"
            - name: "node.ml"
              value: "false"
            - name: "node.remote_cluster_client"  # 各个角色介绍：https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-node.html
              value: "false"
          resources:
            limits:
              cpu: 1000m
              memory: 4096Mi
            requests:
              cpu: 100m
              memory: 1024Mi
          ports:
            - name: http
              containerPort: 9200
              protocol: TCP
            - name: transport
              containerPort: 9300
              protocol: TCP
          volumeMounts:
            - name: elasticsearch-data
              mountPath: /usr/share/elasticsearch/data
  volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
        annotations:
          volume.beta.kubernetes.io/storage-class: nfs-infra
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 100Gi

---
kind: Service
apiVersion: v1
metadata:
  name: elasticsearch-data
  namespace: elasticsearch
  labels:
    component: elasticsearch
    role: data
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    component: elasticsearch
    role: data
  ports:
    - name: transport
      port: 9300
      protocol: TCP