---
apiVersion: v1
kind: ConfigMap
metadata:
  name: elasticsearch-kibana-configmap
  namespace: elasticsearch
data:
  kibana.yml: |
    server.name: kibana
    server.host: "0.0.0.0"
    elasticsearch.hosts: ["http://elasticsearch-client-0.elasticsearch-client.elasticsearch.svc.cluster.local:9200"]
    monitoring.ui.container.elasticsearch.enabled: true

---
kind: Service
apiVersion: v1
metadata:
  name: elasticsearch-kibana
  namespace: elasticsearch
  labels:
    component: elasticsearch
    role: kibana
spec:
  type: NodePort
  selector:
    component: elasticsearch
    role: kibana
  ports:
    - name: kibana
      port: 5601
      protocol: TCP


---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: elasticsearch-kibana
  namespace: elasticsearch
  labels:
    component: elasticsearch
    role: kibana
spec:
  replicas: 1
  selector:
    matchLabels:
      component: elasticsearch
      role: kibana
  template:
    metadata:
      labels:
        component: elasticsearch
        role: kibana
    spec:
      containers:
        - name: elasticsearch-kibana
          image: harbor.freedom.org/elastic/kibana:7.9.2
          env:
            - name: TZ
              value: Asia/Shanghai
          resources:
            limits:
              cpu: 1
          ports:
            - name: kibana
              containerPort: 5601
          volumeMounts:
            - name: kibana-yml
              mountPath: /usr/share/kibana/config/kibana.yml
              subPath: kibana.yml
              readOnly: true
      volumes:
        - name: kibana-yml
          configMap:
            name: elasticsearch-kibana-configmap