apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: elasticsearch-kibana
  namespace: elasticsearch
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
    - host: kibana.ingress-nginx.freedom.org
      http:
        paths:
        - path: /
          backend:
            serviceName: elasticsearch-kibana
            servicePort: 5601