---
- name: systemctl-daemon-reload
  systemd:
    daemon_reload: yes

- name: "restart-gor-record-{{ gor_record_app }}"
  service:
    name: "gor-record-{{ gor_record_app }}"
    state: restarted
    enabled: no

- name: restart-gor-forward
  service:
    name: gor-forward
    state: restarted
    enabled: no