---
# 如果在创建的目录不存在时，并且再加上权限设定，则会递归改变目录owner/group。
#    owner: polkitd
#    group: nfsnobody
- name: create kubernetes nfs pvc directories
  file:
    path: "{{ item }}"
    state: directory
    recurse: yes
    owner: polkitd
    group: nfsnobody
  loop:
    - /data/k8s-pvc-nfs/bj/infra
    - /data/k8s-pvc-nfs/sh/mysql
    - /data/k8s-pvc-nfs/gd/redis