---
- name: create kubernetes pvc directories
  file:
    path: "{{ item }}"
    state: directory
    recurse: yes
    owner: polkitd
    group: nfsnobody
  loop:
    - /data/kubernetes-nfs-pvc/infra
    - /data/kubernetes-nfs-pvc/mysql
    - /data/kubernetes-nfs-pvc/redis-standalone
    - /data/kubernetes-nfs-pvc/redis-cluster