---
- name: create kubernetes pvc directories
  file:
    path: "{{ item }}"
    state: directory
    recurse: yes
    owner: polkitd
    group: nfsnobody
  loop:
    - /kubernetes-datastorage-pvc/infra
    - /kubernetes-datastorage-pvc/mysql
    - /kubernetes-datastorage-pvc/redis