# 不会使用configmap，并且configmap是针对全局的，我更倾向于annotations方案。下面文件理论知识较多。
# https://blog.csdn.net/felix_yujing/article/details/106616962
# https://blog.csdn.net/u012986012/article/details/106571094

# 原生nginx的配置：https://www.cnblogs.com/wulm/p/9817319.html
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: keycloak
  namespace: keycloak
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: keycloak.k8s.freedom.org
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: keycloak
            port:
              number: 8080