---
- name: generate haproxy.service
  template:
    src: haproxy.service.j2
    dest: "{{ systemd_conf_dir }}/haproxy.service"
  notify:
    - systemctl-daemon-reload
    - reload-haproxy
  when: (ansible_distribution == "CentOS" or ansible_distribution == "RedHat") and ansible_distribution_major_version == "7"