---
- name: redis-cluster
  hosts: "[[ item.host ]]"
  user: root
  roles:
    - role: redis
      vars:
        - redis_type: redis_cluster_single_host
        - redis_port: [[ item.redis_port ]]
        - is_install_redis: false