---
- name: redis-cluster
  hosts: "[[ item.host ]]"
  user: root
  roles:
    - role: common

    - role: ruby

    - role: redis
      vars:
        - redis_type: redis_cluster_single_host
        - redis_version: [[ item.redis_version ]]
        - redis_port: ''  # 设置为空，默认值也空，表示忽略配置此时的redis安装过程中的配置文件。
        - is_install_redis: true

{% for redis_port in item.redis_ports  %}
- include: 0-[[ item.service_name ]]-[[ item.host ]]-node-[[ redis_port ]].yml
{% endfor %}