---
- name: install docker-ce {{ docker_version }}
  yum:
    name: "{{ item }}"
    state: present
  loop: "{{ docker_pkgs }}"

- name: start docker service
  service:
    name: docker
    state: started
    enabled: yes

- name: generate docker-ce configuration file
  template:
    src: daemon.json.j2
    dest: /etc/docker/daemon.json
    owner: root
    group: root
  notify: restart-docker