---
- name: remove podman
  yum:
    name: "{{ item }}"
    state: absent
  loop:
    - buildah
    - cockpit-podman
    - podman
    - podman-catatonit
  when: ansible_distribution_major_version == "8"

- name: install docker-ce {{ docker_version }}
  yum:
    name: "{{ item }}"
    state: present
  loop: "{{ docker_pkgs }}"

- name: mkdir /etc/docker directory
  file:
    path: /etc/docker
    state: present

- name: generate docker-ce configuration file
  template:
    src: daemon.json.j2
    dest: /etc/docker/daemon.json
    owner: root
    group: root

- name: restart docker service
  service:
    name: docker
    state: restarted
    enabled: yes