---
- name: install pushgateway {{ pushgateway_version }}
  get_url:
    url: "{{ item.url }}"
    dest: "{{ item.dest }}"
    mode: "0755"
  with_items:
    - { url: "{{ pushgateway_pkg }}", dest: "{{ pushgateway_bin }}" }

- name: create pushgateway configuration directory
  file:
    path: "{{ item }}"
    state: directory
    recurse: yes
    owner: prometheus
    group: prometheus
    mode: '0755'
  loop:
    - "{{ pushgateway_config_dir }}"
      
- name: create pushgateway service
  template:
    src: pushgateway.service.j2
    dest: "{{ systemd_conf_dir }}/pushgateway.service"
  notify:
    - systemctl-daemon-reload
    - enable-pushgateway
    - restart-pushgateway