---
- name: remove docker package from centos extras repo
  yum:
    name: "{{ item }}"
    state: absent
  loop:
    - docker
    - docker-common

- name: install docker-ce
  yum:
    name: docker-ce

- name: config docker
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: "0644"
  with_items:
    - { src: docker/daemon.json, dest: /etc/docker/daemon.json }
  notify:
    - restart docker

- name: restart docker
  service:
    name: docker
    state: restarted
    enabled: yes