---
- name: remove docker package from centos extras repo
  yum:
    name: "{{ item }}"
    state: absent
  loop:
    - docker
    - docker-common

- name: install docker-ce {{ docker_ce_version }}
  yum:
    name: "docker-ce-{{ docker_ce_version }}"

- name: create /etc/docker directory
  file:
    path: /etc/docker
    state: directory

- name: config docker
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: "0644"
  with_items:
    - { src: docker/daemon.json, dest: /etc/docker/daemon.json }
  notify:
    - restart docker

- name: restart docker
  service:
    name: docker
    state: restarted
    enabled: yes

- name: disable swap in /etc/fstab
  replace:
    path: /etc/fstab
    regexp: '(^/dev/mapper/centos-swap.*)'
    replace: '#\1'

- name: disable swap
  shell: swapoff -a

- name: set sysctl configurations to k8s hosts.
  sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    sysctl_set: yes
    reload: yes
    sysctl_file: /etc/sysctl.d/k8s.conf
  with_items:
    - { name: 'net.bridge.bridge-nf-call-ip6tables', value: 1 }
    - { name: 'net.bridge.bridge-nf-call-iptables', value: 1 }
    - { name: 'net.ipv4.ip_forward', value: 1 }
  ignore_errors: yes

- name: install k8s packages
  yum:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - tcl
      - openssl-devel
      - zlib-devel
      - kubeadm-1.16.2-0.x86_64
      - kubectl-1.16.2-0.x86_64
      - kubelet-1.16.2-0.x86_64
      - kubernetes-cni-0.7.5-0.x86_64
  notify: restart kubelet