redis_version: '3.0.3'

redis_file_dir: "/usr/local/src"

redis_file: "redis-{{ redis_version }}.tar.gz"

redis_dest_file: "{{ redis_file_dir }}/redis-{{ redis_version }}.tar.gz"

redis_installation_dir: "/usr/local/redis-{{ redis_version }}"

redis_data_dir: "{{ redis_installation_dir }}/data"

redis_conf_dir: "{{ redis_installation_dir }}/etc"

redis_port: ''