redis_version: '3.0.3'

redis_file: "redis-{{ redis_version }}.tar.gz"

redis_file_dir: "/usr/local/src"

redis_dest_file: "{{ redis_file_dir }}/redis-{{ redis_version }}.tar.gz"

redis_installation_dir: "/usr/local/redis-{{ redis_version }}"

redis_bin_dir: "{{ redis_installation_dir }}/bin"

redis_data_dir: "{{ redis_installation_dir }}/data"

redis_conf_dir: "{{ redis_installation_dir }}/etc"

redis_port: ''  # 默认为空，默认安装时redis时忽略此次的redis.conf文件生成。

redis_replicas: 1   # redis cluster副本个数