ruby_version: 2.6.5

ruby_dest_dir: /usr/local/src

ruby_dest_file: "{{ ruby_dest_dir }}/ruby-{{ ruby_version }}.tar.gz"

ruby_install_dir: "/usr/local/ruby-{{ ruby_version }}"

ruby_bin_path: "{{ ruby_install_dir }}/bin"