# Setup/install tasks.
- include: common.yml

- include: "elasticstack_client_{{ elasticstack_client_type }}.yml"
  when: elasticstack_client_type is defined

- include: elasticsearch.yml
  when: elasticstack_elasticsearch

- include: filebeat.yml
  when: elasticstack_filebeat

- include: kibana.yml
  when: elasticstack_kibana