---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper-nodeport
  namespace: zookeeper
spec:
  type: NodePort
  ports:
    - name: client
      port: 2181
      targetPort: 2181
    - name: server
      port: 2888
      targetPort: 2888
    - name: leader-election
      port: 3888
      targetPort: 3888
  selector:
    k8s-app: zookeeper

---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper-clusterip
  namespace: zookeeper
spec:
  type: ClusterIP
  ports:
    - name: client
      port: 2181
      targetPort: 2181
    - name: server
      port: 2888
      targetPort: 2888
    - name: leader-election
      port: 3888
      targetPort: 3888
  selector:
    k8s-app: zookeeper

---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper
  namespace: zookeeper
spec:
  type: ClusterIP
  ports:
    - name: client
      port: 2181
      targetPort: 2181
    - name: server
      port: 2888
      targetPort: 2888
    - name: leader-election
      port: 3888
      targetPort: 3888
  selector:
    k8s-app: zookeeper