kubernetes_version: "1.22.2"

kubernetes_kernel_version: "lt"

kubernetes_pkgs:
  - "kubeadm-{{ kubernetes_version }}"
  - "kubectl-{{ kubernetes_version }}"
  - "kubelet-{{ kubernetes_version }}"

# 2021-10-02，kubernetes与docker版本有关联关系，目前我使用了1.22.2版本，这个是支持了最新docker版本，即20.10.8。此变量先注释。
#kubernetes_docker_ce_version: "20.10.8"