---
- name: install ingress-nginx pkg
  unarchive:
    src: "{{ ingress_nginx_pkg_url }}"
    dest: "{{ resource_dir }}"
    remote_src: yes

- name: generate ingress-nginx values.yaml
  template:
    src: "values-{{ ingress_nginx_version }}.yaml.j2"
    dest: "{{ resource_dir }}/ingress-nginx/values.yaml"

- name: install ingress-nginx
  shell: |
    export KUBECONFIG=/etc/kubernetes/admin.conf
    kubectl create namespace ingress-nginx
    helm uninstall ingress-nginx -n ingress-nginx
    helm install ingress-nginx . -n ingress-nginx
  args:
    chdir: "{{ resource_dir }}/ingress-nginx"
  ignore_errors: yes
  register: ingress_nginx_status_result

- name: show install ingress-nginx log
  debug:
    msg:
      - "{{ ingress_nginx_status_result.stdout_lines }}"
      - "{{ ingress_nginx_status_result.stderr_lines }}"

- block:
  - name: generate hubble-ui ingress-nginx file
    template:
      src: ingress-nginx-cilium.yml.j2
      dest: ingress-nginx-cilium.yml

  - name: config hubble-ui ingress-nginx
    shell: |
      sleep 60
      echo "Wait ingress-nginx service to start for 60 seconds."
      export KUBECONFIG=/etc/kubernetes/admin.conf
      kubectl apply -f ingress-nginx-cilium.yml
  when: ingress_nginx_enable_hubble_ui