- name: Configure the global environment.
  blockinfile:
    path: /etc/profile
    block: |
      PATH=$PATH:"{{ pkg_link_dir }}/bin"
      export PATH


- name: Create sysctl file of elk.
  file:
    path: /etc/sysctl.d/100-elk.conf
    state: touch


- name: Configure the kernel parameters.
  blockinfile:
    path: "{{ sysctl_file }}"
    block: |
      {{ item.key }} = {{ item.value }}
  with_items:
  - { key: vm.max_map_count, value: 655360 }


# 使用root账号调整系统参数
- name: Apply the limits and kernel settings.
  shell: |
    source /etc/profile
    /sbin/sysctl -p "{{ sysctl_file }}"
    ulimit -n 65535


- name: Configure the elasticsearch.
  template:
    src: "{{ config_template }}"
    dest: "{{ pkg_dest }}/{{ pkg }}/config/{{ config_file }}"
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
    mode: 0644
  notify: Restart elasticsearch.
  when: create_config_file


- name: Configure the elasticsearch service boot on the start.
  blockinfile:
    path: /etc/rc.d/rc.local
    block: |
      su - {{user_name}} -c "{{ elasticsearch_bin }}"


- name: Change mode for the shell start script.
  file:
    path: /etc/rc.d/rc.local
    mode: '0755'