- name: Unarchive elk elasticsearch package.
  unarchive:
    src: "{{ pkg_url }}"
    dest: "{{ pkg_dest }}"
    remote_src: yes
    owner: "{{ user_name }}"
    group: "{{ user_name }}"


- name: Create the elk elasticsearch link.
  file:
    src: "{{ pkg_dest }}/{{ pkg }}"
    dest: "{{ pkg_link_dir }}"
    state: link