---
# cilium_version和cilium_hubble_version要匹配，安装hubble时要看release中的说明。
# https://github.com/cilium/hubble/releases

cilium_version: v0.9.1
cilium_pkg_url: "{{ files_server }}/kubernetes/cilium/{{ cilium_version }}/cilium-linux-amd64.tar.gz"

cilium_hubble_version: v0.8.2
cilium_hubble_pkg_url: "{{ files_server }}/kubernetes/hubble/{{ cilium_hubble_version }}/hubble-linux-amd64.tar.gz"