---
haproxy_version: 1.8.27
haproxy_nic_name: ens192

haproxy_nic_ipaddr: 192.168.2.2
haproxy_nic_netmask: 24
haproxy_nic_gateway: 192.168.2.254

# haproxy_auth_username最好不要使用"@"字符。
haproxy_auth_username: freedom
haproxy_auth_password: freedom

# 在haproxy上配置单网卡多ip，ip地址规划为192.168.2.111-192.168.2.130。
haproxy_ip_list:
  - 192.168.2.111
  - 192.168.2.112
  - 192.168.2.113
  - 192.168.2.114
  - 192.168.2.115
  - 192.168.2.116
  - 192.168.2.117
  - 192.168.2.118
  - 192.168.2.119
  - 192.168.2.120
  - 192.168.2.121
  - 192.168.2.122
  - 192.168.2.123
  - 192.168.2.124
  - 192.168.2.125
  - 192.168.2.126
  - 192.168.2.127
  - 192.168.2.128
  - 192.168.2.129
  - 192.168.2.130

haproxy_service_items:
  - name: kubernetes-apiserver
    mode: tcp
    listen_ip: "{{ haproxy_nic_ipaddr }}"
    listen_port: 6443
    backend_server_mode: static
    backend_server_items:
      - master01.k8s.freedom.org
      - master02.k8s.freedom.org
      - master03.k8s.freedom.org
    backend_server_listen_port: 6443
  - name: kubernetes-ingress-http
    mode: tcp
    listen_ip: "{{ haproxy_nic_ipaddr }}"
    listen_port: 80
    backend_server_mode: static
    backend_server_items:
      - master01.k8s.freedom.org
      - master02.k8s.freedom.org
      - master03.k8s.freedom.org
      - worker01.k8s.freedom.org
      - worker02.k8s.freedom.org
      - worker03.k8s.freedom.org
    backend_server_listen_port: 32080
  - name: kubernetes-ingress-https
    mode: tcp
    listen_ip: "{{ haproxy_nic_ipaddr }}"
    listen_port: 443
    backend_server_mode: static
    backend_server_items:
      - master01.k8s.freedom.org
      - master02.k8s.freedom.org
      - master03.k8s.freedom.org
      - worker01.k8s.freedom.org
      - worker02.k8s.freedom.org
      - worker03.k8s.freedom.org
    backend_server_listen_port: 32443

  # 定义istio转发
  - name: istio-ingressgateway-http
    mode: tcp
    listen_ip: 192.168.2.111
    listen_port: 80
    backend_server_mode: static
    backend_server_items:
      - master01.k8s.freedom.org
      - master02.k8s.freedom.org
      - master03.k8s.freedom.org
      - worker01.k8s.freedom.org
      - worker02.k8s.freedom.org
      - worker03.k8s.freedom.org
    backend_server_listen_port: 30661
  - name: istio-ingressgateway-https
    mode: tcp
    listen_ip: 192.168.2.111
    listen_port: 443
    backend_server_mode: static
    backend_server_items:
      - master01.k8s.freedom.org
      - master02.k8s.freedom.org
      - master03.k8s.freedom.org
      - worker01.k8s.freedom.org
      - worker02.k8s.freedom.org
      - worker03.k8s.freedom.org
    backend_server_listen_port: 30967