---
- name: systemctl-daemon-reload
  systemd:
    daemon_reload: yes

- name: restart-elasticsearch
  service:
    name: elasticsearch
    state: restarted
    enabled: yes

- name: restart-kibana
  service:
    name: kibana
    state: restarted
    enabled: yes

- name: restart-filebeat
  service:
    name: filebeat
    state: restarted
    enabled: yes

- name: reload-httpd
  service:
    name: httpd
    state: reloaded
    enabled: yes