---
- name: install gor {{ gor_record_pkg_ver }} bin
  unarchive:
    src: gor_{{ gor_record_pkg_ver }}_x64.tar.gz
    dest: /usr/local/bin

- name: generate gor replay service
  template:
    src: gor-forward.service.j2
    dest: "{{ systemd_conf_dir }}/gor-forward.service"
  notify:
    - systemctl-daemon-reload
    - restart-gor-forward