ruby_version: 2.6.5

ruby_dest_dir: /usr/local/src

ruby_dest_file: "{{ ruby_dest_dir }}/ruby-{{ ruby_version }}.tar.gz"

ruby_install_dir: "/usr/local/ruby-{{ ruby_version }}"

ruby_bin_path: "{{ ruby_install_dir }}/bin"

is_install_ruby: true   # 默认是安装ruby包的，当redis cluster中存在单机多实例情况下，可以指定不安装。

is_install_gem_pkgs: true   # 默认是安装redis 3.x版本所依赖的redis gem包，当redis cluster中存在单机多实例情况下，可以指定不安装。