---
- name: mkdir gor record traffic directory
  file:
    path: "{{ gor_record_traffic_dir }}/{{ gor_record_app}}"
    state: directory
    recurse: yes
    mode: '0755'

- name: install gor {{ gor_record_pkg_ver }} bin
  unarchive:
    src: gor_{{ gor_record_pkg_ver }}_x64.tar.gz
    dest: /usr/local/bin

- name: install goreplay {{ gor_replay_pkg_ver }} bin
  unarchive:
    src: gor_{{ gor_replay_pkg_ver }}_x64.tar.gz
    dest: /usr/local/bin

- name: generate {{ gor_record_app }} gor record service
  template:
    src: gor-record.service.j2
    dest: "{{ systemd_conf_dir }}/gor-record-{{ gor_record_app }}.service"
  notify:
    - systemctl-daemon-reload
    - "restart-gor-record-{{ gor_record_app }}"