---
- name: generate consul template sub hcl
  template:
    src: consul-template/file_sd-hcl.j2
    dest: "{{ consul_template_config_dir }}/{{ item }}.hcl"
    mode: 0644
  notify: restart-consul-template
  with_items:
    - "{{ file_sd_services }}"

- name: generate consul template ctmpl
  template:
    src: consul-template/file_sd-ctmpl.j2
    dest: "{{ consul_template_data_dir }}/{{ item }}.ctmpl"
    variable_start_string: '[['
    variable_end_string: ']]'
    mode: 0644
  notify: restart-consul-template
  with_items:
    - "{{ file_sd_services }}"