---
- name: install alertmanager {{ alertmanager_version }}
  get_url:
    url: "{{ item.url }}"
    dest: "{{ item.dest }}"
    mode: "0755"
  with_items:
    - { url: "{{ alertmanager_pkg }}", dest: "{{ alertmanager_bin }}" }
    - { url: "{{ amtool_pkg }}", dest: "{{ amtool_bin }}" }

- name: create alertmanager configuration and data directory
  file:
    path: "{{ item }}"
    state: directory
    recurse: yes
    owner: prometheus
    group: prometheus
    mode: '0755'
  loop:
    - "{{ alertmanager_config_dir }}"
    - "{{ alertmanager_data_dir }}"
    - "{{ alertmanager_template_dir }}"

- name: install alertmanager configuration file
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: prometheus
    group: prometheus
    mode: "0644"
    variable_start_string: "[["
    variable_end_string: "]]"
  with_items:
    - { src: alertmanager.yml.j2, dest: "{{ alertmanager_config_dir }}/alertmanager.yml" }
    - { src: template/email.tmpl.j2, dest: "{{ alertmanager_template_dir }}/email.tmpl" }
    - { src: alertmanager.service.j2, dest: "{{ systemd_conf_dir }}/alertmanager.service" }
  notify:
    - systemctl-daemon-reload
    - enable-alertmanager
    - restart-alertmanager