---
- name: copy gem packages
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
    - { src: redis-4.1.3.gem, dest: /tmp/redis-4.1.3.gem }

- name: install gem packages
  command: "{{ ruby_bin_path }}/gem install {{ item.name }} --local"
  with_items:
    - { name: /tmp/redis-4.1.3.gem }