---
- name: install zabbix_agent
  yum:
    name: "{{ item }}"
    state: present
  loop:
    - "{{ zabbix_agent_pkgs }}"

- name: update zabbix agentd config
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
    - {src: "{{ zabbix_version }}/zabbix_agentd.conf.j2", dest: /etc/zabbix/zabbix_agentd.conf }
  notify:
    - restart-zabbix-agent

- name: update zabbix agentd config
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
    - {src: "{{ zabbix_version }}/zabbix_agent2.conf.j2", dest: /etc/zabbix/zabbix_agent2.conf }
  notify:
    - restart-zabbix-agent2
  when: zabbix_agent2_role