---
- name: uninstall zabbix_agent2 packages
  yum:
    name: "{{ item }}"
    state: absent
  loop:
    - "{{ zabbix_agent2_pkgs }}"

- name: install zabbix_agent
  yum:
    name: "{{ item }}"
    state: present
  loop:
    - "{{ zabbix_agent_pkgs }}"
    - "zabbix-get-{{ zabbix_version }}.*"
    - "zabbix-sender-{{ zabbix_version }}.*"

- name: update zabbix agentd config
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
    - {src: "{{ zabbix_version }}/zabbix_agentd.conf.j2", dest: /etc/zabbix/zabbix_agentd.conf }
  notify:
    - restart-zabbix-agent

- name: update zabbix agentd sub-config
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
    - {src: "{{ zabbix_version }}/zabbix_agentd.d/template_db_mysql.conf.j2", dest: /etc/zabbix/zabbix_agentd.d/template_db_mysql.conf }
  notify:
    - restart-zabbix-agent